using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using OetLearner.Api.Data;
using OetLearner.Api.Domain;

namespace OetLearner.Api.Services.Listening;

// ═════════════════════════════════════════════════════════════════════════════
// ListeningDiagnosticSeeder — Stage 2 of OET_LISTENING_MODULE_PATHWAY.md §6.1.
//
// Idempotently materialises the Phase 1 23-item diagnostic mini-test into the
// relational Listening tables (ContentPaper / ListeningPart / ListeningExtract
// / ListeningQuestion / ListeningQuestionOption). The structure is:
//
//   • Part A mini   — 1 consultation extract  → 6 short-answer gap-fills
//                      (British male doctor + Australian female patient)
//                      Sub-skills: L1, L2, L3, L8
//   • Part B mini   — 3 workplace extracts    → 1 MCQ each (3 questions total)
//                      Accents: en-GB, en-AU, en-US (one each)
//                      Sub-skills: L4, L5, L8
//   • Part C mini   — 1 presentation extract  → 6 MCQ
//                      (Australian male professional, stroke rehabilitation)
//                      Sub-skills: L5, L6, L7, L8
//   • Accent test   — 4 short clips           → 1 MCQ each (4 questions total)
//                      Accents: en-GB, en-AU, en-US, en-XX (non-native)
//                      Sub-skills: L8 (accent-specific)
//
//   Total = 6 + 3 + 6 + 4 = 23 items.
//
// Phase 1 audio note:
//   The diagnostic audio is NOT generated by the TTS pipeline yet — extracts
//   are seeded with realistic transcript text but `AudioContentSha = null`.
//   The diagnostic UI must gracefully degrade ("Audio coming soon" + skip-to-
//   question) when AudioContentSha is null. A later phase will wire the TTS
//   worker to synthesise these clips and back-fill the SHAs.
//
// Idempotency:
//   • String slugs for ListeningPart and ListeningQuestion → re-runs in dev
//     are pure no-ops.
//   • Deterministic GUID strings for ListeningExtract.Id (derived from a
//     fixed namespace so the value is stable across machines).
//   • Gated by ListeningDiagnosticSeederOptions.Enabled (default false).
//
// Configuration:
//   Seed:ListeningDiagnostic:Enabled = true   // opt-in
//   Seed:ListeningDiagnostic:PaperId          // override the default PaperId
// ═════════════════════════════════════════════════════════════════════════════

public sealed class ListeningDiagnosticSeederOptions
{
    public const string SectionName = "Seed:ListeningDiagnostic";

    /// <summary>If false, the seeder no-ops (default). Opt in by setting
    /// <c>Seed:ListeningDiagnostic:Enabled = true</c> in appsettings or
    /// via the <c>SEED__LISTENINGDIAGNOSTIC__ENABLED</c> env var.</summary>
    public bool Enabled { get; set; } = false;

    /// <summary>ContentPaper.Id (and slug) used to anchor the diagnostic.
    /// Override if your environment already has a paper with this id.</summary>
    public string PaperId { get; set; } = "listening-diagnostic-phase1";
}

public sealed class ListeningDiagnosticSeeder(
    LearnerDbContext db,
    IOptions<ListeningDiagnosticSeederOptions> opts,
    ILogger<ListeningDiagnosticSeeder> logger)
{
    // Fixed slugs for the four parts. ListeningPart.Id is a string (max 64),
    // so we keep them human-readable for log / DB inspection.
    private const string PartConsultationId = "diagnostic-A";
    private const string PartWorkplaceId = "diagnostic-B";
    private const string PartPresentationId = "diagnostic-C";
    private const string PartAccentId = "diagnostic-accent";

    // Deterministic GUIDs for extracts. Parsing fixed strings keeps the values
    // stable across machines / restarts so re-runs of the seeder are no-ops.
    private static readonly string ExtractAConsultationId = "11111111-aaaa-4000-8000-000000000001";
    private static readonly string ExtractB1Id = "11111111-aaaa-4000-8000-000000000002";
    private static readonly string ExtractB2Id = "11111111-aaaa-4000-8000-000000000003";
    private static readonly string ExtractB3Id = "11111111-aaaa-4000-8000-000000000004";
    private static readonly string ExtractCPresentationId = "11111111-aaaa-4000-8000-000000000005";
    private static readonly string ExtractAccentGBId = "11111111-aaaa-4000-8000-000000000006";
    private static readonly string ExtractAccentAUId = "11111111-aaaa-4000-8000-000000000007";
    private static readonly string ExtractAccentUSId = "11111111-aaaa-4000-8000-000000000008";
    private static readonly string ExtractAccentNNId = "11111111-aaaa-4000-8000-000000000009";

    public async Task SeedAsync(CancellationToken ct)
    {
        var options = opts.Value;
        if (!options.Enabled)
        {
            logger.LogInformation(
                "ListeningDiagnosticSeeder disabled (Seed:ListeningDiagnostic:Enabled=false); skipping.");
            return;
        }

        var paperId = string.IsNullOrWhiteSpace(options.PaperId)
            ? "listening-diagnostic-phase1"
            : options.PaperId.Trim();

        // Probe one of the seeded question Ids — if present we've already run.
        var probeQuestionId = QuestionId("diag-A", 1);
        var alreadySeeded = await db.ListeningQuestions
            .AsNoTracking()
            .AnyAsync(q => q.Id == probeQuestionId, ct);
        if (alreadySeeded)
        {
            logger.LogInformation(
                "ListeningDiagnosticSeeder: diagnostic '{PaperId}' already seeded; skipping.",
                paperId);
            return;
        }

        var now = DateTimeOffset.UtcNow;

        // ───────────────────────── ContentPaper ────────────────────────────
        // The diagnostic anchors against a ContentPaper row (Listening
        // entities cascade via PaperId FK). Create one if it does not exist.
        var paper = await db.ContentPapers.FirstOrDefaultAsync(p => p.Id == paperId, ct);
        if (paper is null)
        {
            paper = new ContentPaper
            {
                Id = paperId,
                Slug = paperId,
                SubtestCode = "listening",
                Title = "Listening Diagnostic (Phase 1)",
                ProfessionId = null,
                AppliesToAllProfessions = true,
                Difficulty = "diagnostic",
                EstimatedDurationMinutes = 30,
                Status = ContentStatus.Draft,
                Priority = 0,
                TagsCsv = "diagnostic,pathway,phase1",
                SourceProvenance = "Seeded by ListeningDiagnosticSeeder (§6.1 of OET_LISTENING_MODULE_PATHWAY.md).",
                ExtractedTextJson = "{}",
                CreatedByAdminId = "system:seed",
                CreatedAt = now,
                UpdatedAt = now,
            };
            db.ContentPapers.Add(paper);
        }

        // ───────────────────────────── Parts ───────────────────────────────
        // Each diagnostic section maps to one ListeningPart row. PartCode is a
        // hard enum (A1, A2, B, C1, C2). We reuse A1 (consultation), B
        // (workplace), C1 (presentation) for the three real-exam-shape parts
        // and repurpose C2 for the accent mini-section so the foreign key /
        // section ordering logic in the rest of the listening surface keeps
        // working without changes.
        var partA = await UpsertPartAsync(
            paperId,
            PartConsultationId,
            ListeningPartCode.A1,
            maxRawScore: 6,
            instructions: "Diagnostic Part A — Consultation (gap-fill).",
            now, ct);

        // Diagnostic keeps a single workplace sub-section (B1) — it is a short
        // placement test, not a full 6-extract Part B exam.
        var partB = await UpsertPartAsync(
            paperId,
            PartWorkplaceId,
            ListeningPartCode.B1,
            maxRawScore: 3,
            instructions: "Diagnostic Part B — Workplace extracts (MCQ).",
            now, ct);

        var partC = await UpsertPartAsync(
            paperId,
            PartPresentationId,
            ListeningPartCode.C1,
            maxRawScore: 6,
            instructions: "Diagnostic Part C — Presentation (MCQ).",
            now, ct);

        var partAccent = await UpsertPartAsync(
            paperId,
            PartAccentId,
            ListeningPartCode.C2,
            maxRawScore: 4,
            instructions: "Diagnostic Accent Test — short clips (MCQ).",
            now, ct);

        // ──────────────────────────── Extracts ─────────────────────────────
        // AudioContentSha intentionally left null — the diagnostic UI must
        // fall back to a "Audio coming soon" placeholder for Phase 1.
        var extractA = await UpsertExtractAsync(
            ExtractAConsultationId, partA.Id, displayOrder: 1,
            ListeningExtractKind.Consultation,
            title: "Consultation: chest pain follow-up",
            accentCode: "en-AU",
            speakersJson: """[{"id":"s1","role":"doctor","gender":"m","accent":"en-GB"},{"id":"s2","role":"patient","gender":"f","accent":"en-AU"}]""",
            transcriptSegmentsJson: TranscriptConsultation(),
            topicCsv: "cardiology,medication-history",
            now, ct);

        var extractB1 = await UpsertExtractAsync(
            ExtractB1Id, partB.Id, displayOrder: 1,
            ListeningExtractKind.Workplace,
            title: "Workplace: nurse-to-nurse handover",
            accentCode: "en-GB",
            speakersJson: """[{"id":"s1","role":"nurse","gender":"f","accent":"en-GB"},{"id":"s2","role":"nurse","gender":"f","accent":"en-GB"}]""",
            transcriptSegmentsJson: TranscriptB1(),
            topicCsv: "handover,adherence",
            now, ct);

        var extractB2 = await UpsertExtractAsync(
            ExtractB2Id, partB.Id, displayOrder: 2,
            ListeningExtractKind.Workplace,
            title: "Workplace: pharmacist briefing",
            accentCode: "en-AU",
            speakersJson: """[{"id":"s1","role":"pharmacist","gender":"m","accent":"en-AU"},{"id":"s2","role":"nurse","gender":"f","accent":"en-AU"}]""",
            transcriptSegmentsJson: TranscriptB2(),
            topicCsv: "pharmacy,dispensing-error",
            now, ct);

        var extractB3 = await UpsertExtractAsync(
            ExtractB3Id, partB.Id, displayOrder: 3,
            ListeningExtractKind.Workplace,
            title: "Workplace: physiotherapist team meeting",
            accentCode: "en-US",
            speakersJson: """[{"id":"s1","role":"physio","gender":"f","accent":"en-US"},{"id":"s2","role":"physio","gender":"m","accent":"en-US"}]""",
            transcriptSegmentsJson: TranscriptB3(),
            topicCsv: "rehabilitation,mobility",
            now, ct);

        var extractC = await UpsertExtractAsync(
            ExtractCPresentationId, partC.Id, displayOrder: 1,
            ListeningExtractKind.Presentation,
            title: "Presentation: stroke rehabilitation outcomes",
            accentCode: "en-AU",
            speakersJson: """[{"id":"s1","role":"specialist","gender":"m","accent":"en-AU"}]""",
            transcriptSegmentsJson: TranscriptPresentation(),
            topicCsv: "stroke,rehabilitation,outcomes",
            now, ct);

        var extractAccentGB = await UpsertExtractAsync(
            ExtractAccentGBId, partAccent.Id, displayOrder: 1,
            ListeningExtractKind.Workplace,
            title: "Accent clip: British (en-GB)",
            accentCode: "en-GB",
            speakersJson: """[{"id":"s1","role":"clinician","gender":"f","accent":"en-GB"}]""",
            transcriptSegmentsJson: TranscriptAccent("The patient was prescribed amoxicillin three times daily for seven days."),
            topicCsv: "accent-test",
            now, ct);

        var extractAccentAU = await UpsertExtractAsync(
            ExtractAccentAUId, partAccent.Id, displayOrder: 2,
            ListeningExtractKind.Workplace,
            title: "Accent clip: Australian (en-AU)",
            accentCode: "en-AU",
            speakersJson: """[{"id":"s1","role":"clinician","gender":"m","accent":"en-AU"}]""",
            transcriptSegmentsJson: TranscriptAccent("She's booked in for an MRI of the lumbar spine tomorrow morning."),
            topicCsv: "accent-test",
            now, ct);

        var extractAccentUS = await UpsertExtractAsync(
            ExtractAccentUSId, partAccent.Id, displayOrder: 3,
            ListeningExtractKind.Workplace,
            title: "Accent clip: American (en-US)",
            accentCode: "en-US",
            speakersJson: """[{"id":"s1","role":"clinician","gender":"f","accent":"en-US"}]""",
            transcriptSegmentsJson: TranscriptAccent("Vital signs are stable; blood pressure one twenty over eighty."),
            topicCsv: "accent-test",
            now, ct);

        var extractAccentNN = await UpsertExtractAsync(
            ExtractAccentNNId, partAccent.Id, displayOrder: 4,
            ListeningExtractKind.Workplace,
            title: "Accent clip: Non-native (en-XX)",
            accentCode: "en-XX",
            speakersJson: """[{"id":"s1","role":"clinician","gender":"m","accent":"en-XX"}]""",
            transcriptSegmentsJson: TranscriptAccent("The wound is healing well; please continue the dressing changes every 48 hours."),
            topicCsv: "accent-test",
            now, ct);

        // Flush parts + extracts before we add questions referencing them.
        await db.SaveChangesAsync(ct);

        // ──────────────────────────── Questions ────────────────────────────
        // Part A — 6 short-answer gap-fills (Questions 1..6).
        AddShortAnswer(paperId, partA.Id, extractA.Id,
            id: QuestionId("diag-A", 1), questionNumber: 1, displayOrder: 1,
            stem: "Patient's main complaint: ___",
            canonical: "chest pain",
            synonyms: new[] { "chest discomfort", "chest pains" },
            subSkills: "L1,L2",
            accent: "en-AU",
            evidence: "Patient says 'I've had this chest pain for a few days.'",
            now);

        AddShortAnswer(paperId, partA.Id, extractA.Id,
            id: QuestionId("diag-A", 2), questionNumber: 2, displayOrder: 2,
            stem: "Duration of symptoms: ___",
            canonical: "three days",
            synonyms: new[] { "3 days", "three day" },
            subSkills: "L1,L3",
            accent: "en-AU",
            evidence: "Doctor: 'And how long has this been going on?' Patient: 'About three days.'",
            now);

        AddShortAnswer(paperId, partA.Id, extractA.Id,
            id: QuestionId("diag-A", 3), questionNumber: 3, displayOrder: 3,
            stem: "Patient's current medication: ___",
            canonical: "metformin",
            synonyms: new[] { "metformin tablets" },
            subSkills: "L3",
            accent: "en-AU",
            evidence: "Patient: 'I take metformin for my diabetes.'",
            now);

        AddShortAnswer(paperId, partA.Id, extractA.Id,
            id: QuestionId("diag-A", 4), questionNumber: 4, displayOrder: 4,
            stem: "Allergy noted: ___",
            canonical: "penicillin",
            synonyms: new[] { "penicillins", "pcn" },
            subSkills: "L1,L8",
            accent: "en-AU",
            evidence: "Patient: 'I'm allergic to penicillin — comes up in a rash.'",
            now);

        AddShortAnswer(paperId, partA.Id, extractA.Id,
            id: QuestionId("diag-A", 5), questionNumber: 5, displayOrder: 5,
            stem: "BP reading: ___",
            canonical: "140 over 90",
            synonyms: new[] { "140/90", "one forty over ninety", "140 90" },
            subSkills: "L1,L2",
            accent: "en-AU",
            evidence: "Doctor: 'Your blood pressure today is one forty over ninety.'",
            now);

        AddShortAnswer(paperId, partA.Id, extractA.Id,
            id: QuestionId("diag-A", 6), questionNumber: 6, displayOrder: 6,
            stem: "Plan for follow-up: ___ days",
            canonical: "ten",
            synonyms: new[] { "10" },
            subSkills: "L2,L8",
            accent: "en-AU",
            evidence: "Doctor: 'I'd like to see you again in ten days for review.'",
            now);

        // Part B — 3 MCQ (Questions 7..9), one per extract.
        AddMcq(paperId, partB.Id, extractB1.Id,
            id: QuestionId("diag-B", 1), questionNumber: 7, displayOrder: 7,
            stem: "What is the nurse's main concern about the patient?",
            options: new (string Key, string Text, bool Correct, ListeningDistractorCategory? Cat)[]
            {
                ("A", "The patient's diet has been poor since admission.", false, ListeningDistractorCategory.WrongSpeaker),
                ("B", "The patient is not taking the prescribed medication regularly.", true, null),
                ("C", "The patient's mobility has worsened overnight.", false, ListeningDistractorCategory.OutOfScope),
            },
            correctKey: "B",
            subSkills: "L4,L8",
            accent: "en-GB",
            now);

        AddMcq(paperId, partB.Id, extractB2.Id,
            id: QuestionId("diag-B", 2), questionNumber: 8, displayOrder: 8,
            stem: "Why is the pharmacist telephoning the ward?",
            options: new (string Key, string Text, bool Correct, ListeningDistractorCategory? Cat)[]
            {
                ("A", "To confirm a substitution because the original drug is out of stock.", true, null),
                ("B", "To report a patient complaint about side effects.", false, ListeningDistractorCategory.ReusedKeyword),
                ("C", "To ask the nurse to collect a sample for testing.", false, ListeningDistractorCategory.OutOfScope),
            },
            correctKey: "A",
            subSkills: "L4,L5",
            accent: "en-AU",
            now);

        AddMcq(paperId, partB.Id, extractB3.Id,
            id: QuestionId("diag-B", 3), questionNumber: 9, displayOrder: 9,
            stem: "What does the senior physiotherapist recommend?",
            options: new (string Key, string Text, bool Correct, ListeningDistractorCategory? Cat)[]
            {
                ("A", "Discharging the patient at the end of the week.", false, ListeningDistractorCategory.TooStrong),
                ("B", "Continuing the current programme without changes.", false, ListeningDistractorCategory.TooWeak),
                ("C", "Adding daily hydrotherapy sessions to the plan.", true, null),
            },
            correctKey: "C",
            subSkills: "L5,L8",
            accent: "en-US",
            now);

        // Part C — 6 MCQ (Questions 10..15) on the stroke-rehab presentation.
        AddMcq(paperId, partC.Id, extractC.Id,
            id: QuestionId("diag-C", 1), questionNumber: 10, displayOrder: 10,
            stem: "What does the speaker identify as the most significant predictor of rehabilitation outcome?",
            options: new (string Key, string Text, bool Correct, ListeningDistractorCategory? Cat)[]
            {
                ("A", "The patient's age at the time of the stroke.", false, ListeningDistractorCategory.ReusedKeyword),
                ("B", "The time from stroke onset to commencement of therapy.", true, null),
                ("C", "The location of the lesion on initial imaging.", false, ListeningDistractorCategory.OutOfScope),
            },
            correctKey: "B",
            subSkills: "L5,L6",
            accent: "en-AU",
            now);

        AddMcq(paperId, partC.Id, extractC.Id,
            id: QuestionId("diag-C", 2), questionNumber: 11, displayOrder: 11,
            stem: "What does the speaker imply about traditional inpatient rehabilitation?",
            options: new (string Key, string Text, bool Correct, ListeningDistractorCategory? Cat)[]
            {
                ("A", "It should be abandoned in favour of home-based care.", false, ListeningDistractorCategory.TooStrong),
                ("B", "It works well for a narrower group of patients than once assumed.", true, null),
                ("C", "It produces equivalent outcomes regardless of stroke severity.", false, ListeningDistractorCategory.OppositeMeaning),
            },
            correctKey: "B",
            subSkills: "L6,L7",
            accent: "en-AU",
            now);

        AddMcq(paperId, partC.Id, extractC.Id,
            id: QuestionId("diag-C", 3), questionNumber: 12, displayOrder: 12,
            stem: "Which patient group benefits most from the new community programme?",
            options: new (string Key, string Text, bool Correct, ListeningDistractorCategory? Cat)[]
            {
                ("A", "Patients with mild to moderate motor deficits.", true, null),
                ("B", "Patients with severe aphasia and limited mobility.", false, ListeningDistractorCategory.WrongSpeaker),
                ("C", "Patients under the age of 50 with no co-morbidities.", false, ListeningDistractorCategory.OutOfScope),
            },
            correctKey: "A",
            subSkills: "L5,L8",
            accent: "en-AU",
            now);

        AddMcq(paperId, partC.Id, extractC.Id,
            id: QuestionId("diag-C", 4), questionNumber: 13, displayOrder: 13,
            stem: "What concern does the speaker raise about the published evidence?",
            options: new (string Key, string Text, bool Correct, ListeningDistractorCategory? Cat)[]
            {
                ("A", "The cohorts studied so far have been too small to generalise.", true, null),
                ("B", "The funding bodies have refused to support further trials.", false, ListeningDistractorCategory.OutOfScope),
                ("C", "The outcome measures used are obsolete.", false, ListeningDistractorCategory.TooStrong),
            },
            correctKey: "A",
            subSkills: "L6,L7",
            accent: "en-AU",
            now);

        AddMcq(paperId, partC.Id, extractC.Id,
            id: QuestionId("diag-C", 5), questionNumber: 14, displayOrder: 14,
            stem: "How does the speaker feel about technology-assisted rehabilitation?",
            options: new (string Key, string Text, bool Correct, ListeningDistractorCategory? Cat)[]
            {
                ("A", "Enthusiastic — it is already the standard of care.", false, ListeningDistractorCategory.TooStrong),
                ("B", "Cautiously optimistic — promising but in need of further evidence.", true, null),
                ("C", "Sceptical — it adds cost without clinical benefit.", false, ListeningDistractorCategory.OppositeMeaning),
            },
            correctKey: "B",
            subSkills: "L7",
            accent: "en-AU",
            now);

        AddMcq(paperId, partC.Id, extractC.Id,
            id: QuestionId("diag-C", 6), questionNumber: 15, displayOrder: 15,
            stem: "What does the speaker recommend clinicians do next?",
            options: new (string Key, string Text, bool Correct, ListeningDistractorCategory? Cat)[]
            {
                ("A", "Refer all eligible patients to the trial immediately.", false, ListeningDistractorCategory.TooStrong),
                ("B", "Audit their current pathways against the new criteria.", true, null),
                ("C", "Wait for national guidelines before changing practice.", false, ListeningDistractorCategory.TooWeak),
            },
            correctKey: "B",
            subSkills: "L6,L8",
            accent: "en-AU",
            now);

        // Accent test — 4 MCQ (Questions 16..19), one per accent.
        AddMcq(paperId, partAccent.Id, extractAccentGB.Id,
            id: QuestionId("diag-accent", 1), questionNumber: 16, displayOrder: 16,
            stem: "What medication was the patient prescribed?",
            options: new (string Key, string Text, bool Correct, ListeningDistractorCategory? Cat)[]
            {
                ("A", "Amoxicillin three times daily for seven days.", true, null),
                ("B", "Ampicillin twice daily for ten days.", false, ListeningDistractorCategory.ReusedKeyword),
                ("C", "Azithromycin once daily for three days.", false, ListeningDistractorCategory.ReusedKeyword),
            },
            correctKey: "A",
            subSkills: "L8",
            accent: "en-GB",
            now);

        AddMcq(paperId, partAccent.Id, extractAccentAU.Id,
            id: QuestionId("diag-accent", 2), questionNumber: 17, displayOrder: 17,
            stem: "Which investigation is scheduled?",
            options: new (string Key, string Text, bool Correct, ListeningDistractorCategory? Cat)[]
            {
                ("A", "A CT scan of the abdomen.", false, ListeningDistractorCategory.ReusedKeyword),
                ("B", "An MRI of the lumbar spine.", true, null),
                ("C", "An X-ray of the cervical spine.", false, ListeningDistractorCategory.ReusedKeyword),
            },
            correctKey: "B",
            subSkills: "L8",
            accent: "en-AU",
            now);

        AddMcq(paperId, partAccent.Id, extractAccentUS.Id,
            id: QuestionId("diag-accent", 3), questionNumber: 18, displayOrder: 18,
            stem: "What is the patient's blood pressure?",
            options: new (string Key, string Text, bool Correct, ListeningDistractorCategory? Cat)[]
            {
                ("A", "110 over 70.", false, ListeningDistractorCategory.ReusedKeyword),
                ("B", "120 over 80.", true, null),
                ("C", "140 over 90.", false, ListeningDistractorCategory.ReusedKeyword),
            },
            correctKey: "B",
            subSkills: "L8",
            accent: "en-US",
            now);

        AddMcq(paperId, partAccent.Id, extractAccentNN.Id,
            id: QuestionId("diag-accent", 4), questionNumber: 19, displayOrder: 19,
            stem: "How often should the dressing be changed?",
            options: new (string Key, string Text, bool Correct, ListeningDistractorCategory? Cat)[]
            {
                ("A", "Every 24 hours.", false, ListeningDistractorCategory.ReusedKeyword),
                ("B", "Every 48 hours.", true, null),
                ("C", "Every 72 hours.", false, ListeningDistractorCategory.ReusedKeyword),
            },
            correctKey: "B",
            subSkills: "L8",
            accent: "en-XX",
            now);

        await db.SaveChangesAsync(ct);

        logger.LogInformation(
            "ListeningDiagnosticSeeder: seeded diagnostic '{PaperId}' — {Parts} part(s), {Extracts} extract(s), {Questions} question(s).",
            paperId, 4, 9, 19);
    }

    // ────────────────────────── helpers ────────────────────────────────────

    private static string QuestionId(string prefix, int n) => $"{prefix}-Q{n}";

    private async Task<ListeningPart> UpsertPartAsync(
        string paperId,
        string partId,
        ListeningPartCode partCode,
        int maxRawScore,
        string instructions,
        DateTimeOffset now,
        CancellationToken ct)
    {
        var existing = await db.ListeningParts.FirstOrDefaultAsync(p => p.Id == partId, ct);
        if (existing is not null) return existing;

        var part = new ListeningPart
        {
            Id = partId,
            PaperId = paperId,
            PartCode = partCode,
            MaxRawScore = maxRawScore,
            Instructions = instructions,
            CreatedAt = now,
            UpdatedAt = now,
        };
        db.ListeningParts.Add(part);
        return part;
    }

    private async Task<ListeningExtract> UpsertExtractAsync(
        string id,
        string partId,
        int displayOrder,
        ListeningExtractKind kind,
        string title,
        string? accentCode,
        string speakersJson,
        string transcriptSegmentsJson,
        string? topicCsv,
        DateTimeOffset now,
        CancellationToken ct)
    {
        var existing = await db.ListeningExtracts.FirstOrDefaultAsync(e => e.Id == id, ct);
        if (existing is not null) return existing;

        var extract = new ListeningExtract
        {
            Id = id,
            ListeningPartId = partId,
            DisplayOrder = displayOrder,
            Kind = kind,
            Title = title,
            AccentCode = accentCode,
            SpeakersJson = speakersJson,
            AudioStartMs = null,
            AudioEndMs = null,
            ReplayInLearningOnly = true,
            TranscriptSegmentsJson = transcriptSegmentsJson,
            TopicCsv = topicCsv,
            DifficultyRating = 3,
            // Phase 1: TTS pipeline does NOT synthesise diagnostic audio yet.
            // The diagnostic UI must show "Audio coming soon" while this is null.
            AudioContentSha = null,
            TtsVoice = null,
            TtsModelVariant = null,
            CreatedAt = now,
            UpdatedAt = now,
        };
        db.ListeningExtracts.Add(extract);
        return extract;
    }

    private void AddShortAnswer(
        string paperId,
        string partId,
        string extractId,
        string id,
        int questionNumber,
        int displayOrder,
        string stem,
        string canonical,
        IEnumerable<string> synonyms,
        string subSkills,
        string accent,
        string evidence,
        DateTimeOffset now)
    {
        var synonymList = synonyms?.ToArray() ?? Array.Empty<string>();
        var q = new ListeningQuestion
        {
            Id = id,
            PaperId = paperId,
            ListeningPartId = partId,
            ListeningExtractId = extractId,
            QuestionNumber = questionNumber,
            DisplayOrder = displayOrder,
            Points = 1,
            QuestionType = ListeningQuestionType.ShortAnswer,
            Stem = stem,
            CorrectAnswerJson = System.Text.Json.JsonSerializer.Serialize(canonical),
            AcceptedSynonymsJson = synonymList.Length > 0
                ? System.Text.Json.JsonSerializer.Serialize(synonymList)
                : null,
            CaseSensitive = false,
            ExplanationMarkdown = null,
            SkillTag = null,
            SubSkillTagsCsv = subSkills,
            Accent = accent,
            TranscriptEvidenceText = evidence,
            DifficultyLevel = 3,
            Version = 1,
            CreatedAt = now,
            UpdatedAt = now,
        };
        db.ListeningQuestions.Add(q);
    }

    private void AddMcq(
        string paperId,
        string partId,
        string extractId,
        string id,
        int questionNumber,
        int displayOrder,
        string stem,
        (string Key, string Text, bool Correct, ListeningDistractorCategory? Cat)[] options,
        string correctKey,
        string subSkills,
        string accent,
        DateTimeOffset now)
    {
        var q = new ListeningQuestion
        {
            Id = id,
            PaperId = paperId,
            ListeningPartId = partId,
            ListeningExtractId = extractId,
            QuestionNumber = questionNumber,
            DisplayOrder = displayOrder,
            Points = 1,
            QuestionType = ListeningQuestionType.MultipleChoice3,
            Stem = stem,
            CorrectAnswerJson = System.Text.Json.JsonSerializer.Serialize(correctKey),
            AcceptedSynonymsJson = null,
            CaseSensitive = false,
            ExplanationMarkdown = null,
            SkillTag = null,
            SubSkillTagsCsv = subSkills,
            Accent = accent,
            DifficultyLevel = 3,
            Version = 1,
            CreatedAt = now,
            UpdatedAt = now,
        };
        db.ListeningQuestions.Add(q);

        var order = 0;
        foreach (var (key, text, correct, cat) in options)
        {
            order++;
            db.ListeningQuestionOptions.Add(new ListeningQuestionOption
            {
                Id = $"{id}-opt-{key}",
                ListeningQuestionId = id,
                OptionKey = key,
                DisplayOrder = order,
                Text = text,
                IsCorrect = correct,
                DistractorCategory = correct ? null : cat,
                WhyWrongMarkdown = null,
                Version = 1,
            });
        }
    }

    // ───────────────────── transcript placeholders ─────────────────────────
    // Phase 1 transcripts are short, healthcare-themed, and good enough for
    // the UI text track. The TTS pipeline will replace these with real audio
    // in a later phase.

    private static string TranscriptConsultation() => """
        [
          {"startMs":0,"endMs":4000,"speakerId":"s1","text":"Good morning. Can you tell me what's brought you in today?"},
          {"startMs":4000,"endMs":9000,"speakerId":"s2","text":"I've had this chest pain for a few days now. It comes and goes."},
          {"startMs":9000,"endMs":12000,"speakerId":"s1","text":"And how long has this been going on?"},
          {"startMs":12000,"endMs":15000,"speakerId":"s2","text":"About three days."},
          {"startMs":15000,"endMs":19000,"speakerId":"s1","text":"Any medications you're currently taking?"},
          {"startMs":19000,"endMs":22000,"speakerId":"s2","text":"I take metformin for my diabetes."},
          {"startMs":22000,"endMs":26000,"speakerId":"s1","text":"Any allergies I should be aware of?"},
          {"startMs":26000,"endMs":30000,"speakerId":"s2","text":"I'm allergic to penicillin — comes up in a rash."},
          {"startMs":30000,"endMs":35000,"speakerId":"s1","text":"Your blood pressure today is one forty over ninety."},
          {"startMs":35000,"endMs":40000,"speakerId":"s1","text":"I'd like to see you again in ten days for review."}
        ]
        """;

    private static string TranscriptB1() => """
        [
          {"startMs":0,"endMs":4000,"speakerId":"s1","text":"Has Mrs Patel been taking her tablets this morning?"},
          {"startMs":4000,"endMs":9000,"speakerId":"s2","text":"That's actually what I wanted to flag — she's been skipping the lunchtime dose for two days."}
        ]
        """;

    private static string TranscriptB2() => """
        [
          {"startMs":0,"endMs":4000,"speakerId":"s1","text":"We're out of the original brand, so I've substituted it with the generic equivalent."},
          {"startMs":4000,"endMs":7000,"speakerId":"s2","text":"Same dose? Anything we need to change on the chart?"}
        ]
        """;

    private static string TranscriptB3() => """
        [
          {"startMs":0,"endMs":4000,"speakerId":"s1","text":"Progress has plateaued — I think we should layer in hydrotherapy."},
          {"startMs":4000,"endMs":7000,"speakerId":"s2","text":"Daily?"},
          {"startMs":7000,"endMs":9000,"speakerId":"s1","text":"Yes, daily for the next fortnight."}
        ]
        """;

    private static string TranscriptPresentation() => """
        [
          {"startMs":0,"endMs":6000,"speakerId":"s1","text":"Good afternoon. Today I want to discuss what we've learned about stroke rehabilitation outcomes over the last decade."},
          {"startMs":6000,"endMs":14000,"speakerId":"s1","text":"The single strongest predictor we've identified is not age, not lesion site, but the interval between onset and the start of therapy."},
          {"startMs":14000,"endMs":22000,"speakerId":"s1","text":"That said, traditional inpatient rehabilitation continues to play a role — though, as the evidence accumulates, for a narrower group of patients than we once assumed."},
          {"startMs":22000,"endMs":30000,"speakerId":"s1","text":"Our community-based programme has been particularly effective for patients with mild to moderate motor deficits."},
          {"startMs":30000,"endMs":38000,"speakerId":"s1","text":"I should note — the cohorts we've studied have been relatively small, so generalising too quickly is a risk."},
          {"startMs":38000,"endMs":46000,"speakerId":"s1","text":"Technology-assisted rehabilitation is promising. I am cautiously optimistic, but we need larger trials before we declare it standard practice."},
          {"startMs":46000,"endMs":54000,"speakerId":"s1","text":"So what should clinicians do? My recommendation: audit your current pathways against the new criteria, and identify patients who could benefit from earlier referral."}
        ]
        """;

    private static string TranscriptAccent(string singleLine) =>
        System.Text.Json.JsonSerializer.Serialize(new[]
        {
            new
            {
                startMs = 0,
                endMs = 5000,
                speakerId = "s1",
                text = singleLine,
            }
        });
}
