import type { RuntimeSettingsResponse } from './runtime-settings-types';
import type { SectionId } from './runtime-settings-fields';

export const SECTION_META: { id: SectionId; title: string; description: string }[] = [
  { id: 'email', title: 'Email (Brevo + SMTP)', description: 'Transactional email delivery via Brevo with SMTP fallback.' },
  { id: 'billing', title: 'Billing (Stripe)', description: 'Stripe Checkout, Customer Portal, and webhook signing.' },
  { id: 'paypal', title: 'Payments: PayPal', description: 'PayPal Expanded (embedded) checkout + redirect fallback. Client ID is public (used by the browser SDK); Secret and Webhook ID stay server-side. Enable embedded card fields if your account has Advanced Cards eligibility.' },
  { id: 'sentry', title: 'Sentry', description: 'Error reporting and performance monitoring.' },
  { id: 'backup', title: 'Backup S3', description: 'Off-site database and media backup destination.' },
  { id: 'oauth', title: 'OAuth (Google + Apple + Facebook)', description: 'Social sign-in providers.' },
  { id: 'push', title: 'Push (Browser + APNs + FCM)', description: 'Browser VAPID and native mobile push notifications via Apple and Firebase.' },
  { id: 'uploadScanner', title: 'Upload Scanner (ClamAV)', description: 'Antivirus scanning for learner/admin uploads.' },
  { id: 'zoom', title: 'Zoom Live Classes', description: 'Server-to-server OAuth, Meeting SDK, and webhook verification.' },
  { id: 'speakingWhisper', title: 'Speaking: Whisper Transcription', description: 'Legacy fallback. The whisper-asr row in Admin → AI Providers takes precedence when it has an API key — configure Whisper there to cover Speaking, Pronunciation, and Conversation transcription with one key.' },
  { id: 'speakingLiveKit', title: 'Speaking: LiveKit (Live Rooms)', description: 'LiveKit Cloud WebRTC for live tutor rooms and egress recording.' },
  { id: 'speakingAi', title: 'Speaking: AI Providers', description: 'Anthropic (Claude scoring + patient turns) and ElevenLabs (AI patient TTS voice).' },
  { id: 'speakingStorage', title: 'Speaking: Recording Storage (AWS S3)', description: 'AWS S3 bucket for speaking session recording archive.' },
  { id: 'speakingCompliance', title: 'Speaking: Compliance & Retention', description: 'Consent versioning, recording retention windows, and audit log retention.' },
  { id: 'speakingFeatures', title: 'Speaking: Feature Flags', description: 'Controls the Speaking v2 module rollout to learners.' },
  { id: 'checkoutCom', title: 'Payments: Checkout.com', description: 'Premium MENA + global cards (3DS2, Apple/Google Pay, mada). Keys override env config; webhook verification uses the same key.' },
  { id: 'bunnyStream', title: 'Video Library: Bunny Stream', description: 'Bunny Stream hosting for the Video Library — library credentials, CDN token-auth key, webhook secret, and the app-only playback attestation keys. Test does a non-destructive Bunny API probe. Videos play only in the desktop/mobile apps; leave disabled to keep the whole feature dormant.' },
  { id: 'paymob', title: 'Payments: Paymob', description: 'Egypt — cards, Meeza, Fawry, wallets. Keys override env config; webhook verification uses the same HMAC secret.' },
  { id: 'easyKash', title: 'Payments: EasyKash', description: 'Egypt hosted Direct-Pay — cards, wallets, Fawry, instalments. Appears at checkout (under Pay globally, below PayPal) only once BOTH the API key and HMAC secret are set. Set the EasyKash dashboard Callback URL to /v1/payment/webhooks/easykash. Currency mode toggles GBP passthrough vs FX-convert to EGP.' },
  { id: 'payTabs', title: 'Payments: PayTabs', description: 'Gulf + Egypt — cards, mada, KNET, Apple Pay. Keys override env config; webhook verification uses the same key.' },
  { id: 'soketi', title: 'Realtime: Soketi', description: 'Server-side websocket push. The browser client key comes from NEXT_PUBLIC_* env — changes here affect server dispatch only.' },
  { id: 'dataRetention', title: 'Data Retention', description: 'Retention windows for high-volume event tables (analytics, audit, payment webhooks, notification attempts) and the sweeper cadence.' },
  { id: 'expertAutoAssignment', title: 'Expert Auto-Assignment', description: 'Writing-review auto-assignment loop: enablement, SLA windows, per-expert load cap, and batch sizes.' },
  { id: 'passwordPolicy', title: 'Password Policy', description: 'Complexity requirements and the HaveIBeenPwned breach check for new/changed passwords.' },
  { id: 'aiAssistant', title: 'AI Assistant', description: 'Codebase AI assistant orchestration: ReAct loop limits, circuit breaker, command/backup limits, and embedding/indexing knobs. Provider API keys live in AI Providers.' },
  { id: 'aiGateway', title: 'AI Gateway & Tooling', description: 'Grounded gateway defaults (provider, model, temperature, max tokens) and AI tool knobs (tool-call cap, grant cache, external-network allowlist/budget). API key managed in AI Providers.' },
  { id: 'writing', title: 'Writing Module', description: 'Writing V2 feature flags and tunables: cron kill switch, coach hint limits/cost cap, OCR pipeline + GCV key, appeals, tutor-review queue gates, plan regen, and grade idempotency.' },
  { id: 'platform', title: 'Platform', description: 'Public-facing API/Web base URLs (external auth callbacks, CSRF origin validation) and the fallback email domain for synthesized learner emails.' },
  { id: 'firebaseOtp', title: 'Firebase OTP', description: 'Firebase Phone Auth as the SMS OTP transport for password reset and new-device approval. Email verification stays on Brevo. This is not the login authority and does not replace FCM push credentials.' },
  { id: 'messaging', title: 'Messaging (SMS / WhatsApp)', description: 'Billing-notification channels: Twilio SMS and Meta WhatsApp Business Cloud. Auth Token and Access Token are stored encrypted.' },
  { id: 'fx', title: 'FX / Currency', description: 'Currency conversion provider for dynamic pricing. The API key is stored encrypted; empty key falls back to offline seed rates.' },
  { id: 'billingCore', title: 'Billing Core (non-gateway)', description: 'Core billing knobs: default currency/region, wallet currency + top-up tiers, and webhook replay window/attempts. Gateway credentials live in the Billing/Stripe/PayPal/Checkout.com/Paymob/PayTabs sections; the PayPal live/sandbox switch is in the Payments: PayPal section.' },
  { id: 'storage', title: 'Storage (S3 / Object Store)', description: 'S3-compatible object storage (AWS S3, DigitalOcean Spaces, Cloudflare R2) and content-upload limits. Access keys are stored encrypted. Filesystem paths stay env-only; provider switch needs a restart.' },
  { id: 'pdfExtraction', title: 'PDF Extraction', description: 'PDF text-extraction provider and Azure Document Intelligence OCR fallback. The Azure key is stored encrypted.' },
  { id: 'pronunciation', title: 'Pronunciation', description: 'Pronunciation ASR provider selection, region/locale, Whisper/Gemini base-urls + models, audio limits, retention, and free-tier gating. API keys live in Admin → AI Providers.' },
  { id: 'authTokens', title: 'Auth Tokens', description: 'Access/refresh/OTP token lifetimes and the authenticator issuer label. Signing keys, issuer, and audience stay env-only (trust anchors).' },
  { id: 'webPush', title: 'Web Push', description: 'Browser web-push master toggle. VAPID keys are configured in the Push section.' },
  { id: 'support', title: 'Support WhatsApp', description: 'The public WhatsApp number learners message to send payment proof, plus the pre-filled message. Shown next to every package and on every checkout/billing surface. Stored in plaintext — it is a public number, not a secret. Separate from the Messaging section, which holds the Meta Cloud API sender credentials for automated notifications.' },
  { id: 'security', title: 'Security', description: 'Course Platform Security Requirements: single active session enforcement, sign-in risk mode, and device-verification policy. See Admin → Security for the events feed and per-account session/device management.' },
  { id: 'videoProtection', title: 'Video Capture Protection', description: 'Response to detected screen capture/recording during video playback.' },
];

export function emptyResponse(): RuntimeSettingsResponse {
  return {
    email: {
      brevoApiKey: '',
      brevoEmailVerificationTemplateId: null,
      brevoPasswordResetTemplateId: null,
      smtpHost: '',
      smtpPort: null,
      smtpUsername: '',
      smtpPassword: '',
      smtpFromAddress: '',
      smtpFromName: '',
      authFromAddress: '',
      authFromName: '',
      marketingFromAddress: '',
      marketingFromName: '',
      productFromAddress: '',
      productFromName: '',
      supportFromAddress: '',
      supportFromName: '',
      brevoWelcomeTemplateId: null,
      brevoPasswordChangedTemplateId: null,
      brevoMfaEnabledTemplateId: null,
      brevoAdminInviteTemplateId: null,
      brevoSecurityAlertTemplateId: null,
      brevoReviewCompletedTemplateId: null,
      brevoWebhookSecret: '',
      brevoEnabled: null,
      smtpEnabled: null,
      smtpEnableSsl: null,
    },
    billing: {
      stripeSecretKey: '',
      stripePublishableKey: '',
      stripeWebhookSecret: '',
      stripeSuccessUrl: '',
      stripeCancelUrl: '',
      publicAppBaseUrl: '',
      paypalClientId: '',
      paypalClientSecret: '',
      paypalWebhookId: '',
      paypalSuccessUrl: '',
      paypalCancelUrl: '',
      paypalAdvancedCardsEnabled: null,
    },
    sentry: { dsn: '', environment: '', sampleRate: null },
    backup: {
      s3Url: '',
      awsAccessKeyId: '',
      awsSecretAccessKey: '',
      gpgPassphrase: '',
      alertWebhook: '',
    },
    oauth: {
      googleClientId: '',
      googleClientSecret: '',
      appleClientId: '',
      appleTeamId: '',
      appleKeyId: '',
      applePrivateKey: '',
      facebookAppId: '',
      facebookAppSecret: '',
      linkedInClientId: '',
      linkedInClientSecret: '',
      linkedInEnabled: null,
      googleAuthEnabled: null,
      facebookAuthEnabled: null,
    },
    push: {
      apnsKeyId: '',
      apnsTeamId: '',
      apnsBundleId: '',
      apnsAuthKey: '',
      fcmServiceAccountJson: '',
      fcmProjectId: '',
      vapidSubject: '',
      vapidPublicKey: '',
      vapidPrivateKey: '',
    },
    uploadScanner: {
      provider: '',
      host: '',
      port: null,
      timeoutSeconds: null,
      failClosedOnError: null,
    },
    zoom: {
      enabled: null,
      accountId: '',
      clientId: '',
      clientSecret: '',
      apiBaseUrl: '',
      tokenUrl: '',
      hostUserId: '',
      meetingSdkKey: '',
      meetingSdkSecret: '',
      webhookSecretToken: '',
      webhookRetryToleranceSeconds: null,
      allowSandboxFallback: null,
    },
    speakingWhisper: {
      apiKey: '',
      baseUrl: '',
      model: '',
      isConfigured: false,
    },
    speakingLiveKit: {
      provider: '',
      apiKey: '',
      apiSecret: '',
      wssUrl: '',
      webhookSigningSecret: '',
      egressBucket: '',
      defaultMaxDurationSeconds: null,
      egressEnabled: null,
      isEnabled: false,
    },
    speakingAi: {
      anthropicApiKey: '',
      elevenLabsApiKey: '',
      isAnthropicConfigured: false,
      isElevenLabsConfigured: false,
    },
    speakingStorage: {
      awsAccessKeyId: '',
      awsSecretAccessKey: '',
      region: '',
      bucket: '',
      isConfigured: false,
    },
    speakingCompliance: {
      currentConsentVersion: '',
      currentLiveVideoConsentVersion: '',
      retentionDaysDefault: null,
      retentionDaysWhenTutorReviewed: null,
      auditLogRetentionDays: null,
    },
    speakingFeatures: {
      speakingV2Enabled: null,
    },
    checkoutCom: {
      apiBaseUrl: '',
      secretKey: '',
      publicKey: '',
      processingChannelId: '',
      webhookSecret: '',
      successUrl: '',
      cancelUrl: '',
      isConfigured: false,
    },
    bunnyStream: {
      enabled: null,
      libraryId: '',
      apiKey: '',
      cdnHostname: '',
      tokenAuthKey: '',
      webhookSecret: '',
      collectionId: '',
      playbackTokenTtlSeconds: null,
      videoAttestationKeysJson: '',
      videoAttestationKeys: '',
      videoAttestationKeyIds: [],
      isConfigured: false,
    },
    paymob: {
      apiBaseUrl: '',
      apiKey: '',
      merchantId: '',
      hmacSecret: '',
      integrationIdsJson: '',
      iframeId: null,
      successUrl: '',
      cancelUrl: '',
      isConfigured: false,
    },
    easyKash: {
      apiBaseUrl: '',
      apiKey: '',
      hmacSecret: '',
      paymentOptionsCsv: '',
      currencyMode: 'passthrough',
      successUrl: '',
      cancelUrl: '',
      isConfigured: false,
    },
    payTabs: {
      apiBaseUrl: '',
      serverKey: '',
      profileId: '',
      webhookSecret: '',
      successUrl: '',
      cancelUrl: '',
      isConfigured: false,
    },
    soketi: {
      host: '',
      port: null,
      appId: '',
      appKey: '',
      appSecret: '',
      useTls: null,
      enabled: null,
    },
    dataRetention: {
      analyticsEventsDays: null,
      auditEventsDays: null,
      paymentWebhookEventsDays: null,
      paymentWebhookPiiNullOutAgeDays: null,
      notificationDeliveryAttemptsDays: null,
      securityEventsDays: null,
      sweepIntervalHours: null,
      batchSize: null,
    },
    expertAutoAssignment: {
      enabled: null,
      pollingIntervalSeconds: null,
      slaEscalationIntervalSeconds: null,
      slaHoursStandard: null,
      slaHoursExpress: null,
      maxActiveAssignmentsPerExpert: null,
      lookbackHoursForLoad: null,
      batchSize: null,
    },
    passwordPolicy: {
      minimumLength: null,
      requireMixedCase: null,
      requireDigit: null,
      requireSymbol: null,
      breachCheckEnabled: null,
      breachApiBaseUrl: '',
      breachApiTimeoutSeconds: null,
    },
    aiAssistant: {
      globalEnabled: null,
      requireApprovalAlways: null,
      maxIterations: null,
      maxContextMessages: null,
      backupRetentionDays: null,
      maxWriteFileSizeBytes: null,
      commandTimeoutSeconds: null,
      circuitBreakerMaxFailures: null,
      circuitBreakerFailureWindowSeconds: null,
      circuitBreakerMaxWrites: null,
      circuitBreakerWriteWindowSeconds: null,
      embeddingModel: '',
      maxChunkTokens: null,
    },
    aiGateway: {
      aiProviderProviderId: '',
      aiProviderBaseUrl: '',
      aiProviderDefaultModel: '',
      aiProviderReasoningEffort: '',
      aiProviderDefaultMaxTokens: null,
      aiProviderDefaultTemperature: null,
      aiToolMaxToolCallsPerCompletion: null,
      aiToolFeatureGrantCacheSeconds: null,
      aiToolAllowedExternalHostsCsv: '',
      aiToolExternalNetworkPerUserDailyCalls: null,
      aiToolExternalNetworkTimeoutMilliseconds: null,
      aiToolExternalNetworkMaxResponseBytes: null,
    },
    writing: {
      cronsEnabled: null,
      coachEnabled: null,
      coachDailyCostCapPerLearnerUsd: null,
      coachMaxHintsPerSession: null,
      coachMinSecondsBetweenHints: null,
      gcvApiKey: '',
      ocrEnabled: null,
      appealsEnabled: null,
      tutorReviewQueueMaxDepth: null,
      tutorReviewMaxWaitHours: null,
      maxDailyPlanRegenerationsPerDay: null,
      gradeIdempotencyTtlHours: null,
    },
    platform: {
      publicApiBaseUrl: '',
      publicWebBaseUrl: '',
      fallbackEmailDomain: '',
    },
    messaging: {
      twilioEnabled: null,
      twilioApiBaseUrl: '',
      twilioAccountSid: '',
      twilioAuthToken: '',
      twilioFromNumber: '',
      twilioMessagingServiceSid: '',
      whatsAppEnabled: null,
      whatsAppApiBaseUrl: '',
      whatsAppAccessToken: '',
      whatsAppPhoneNumberId: '',
      whatsAppFallbackTemplateName: '',
    },
    fx: {
      baseCurrency: '',
      apiKey: '',
      apiBaseUrl: '',
      dynamicPricingEnabled: null,
    },
    billingCore: {
      checkoutBaseUrl: '',
      webhookMaxAgeSeconds: null,
      webhookMaxAttempts: null,
      defaultCurrency: '',
      defaultRegion: '',
      walletCurrency: '',
      walletTopUpTiersJson: '',
      paypalUseSandbox: null,
      paypalApiBaseUrl: '',
    },
    storage: {
      provider: '',
      bucketName: '',
      endpointUrl: '',
      accessKeyId: '',
      secretAccessKey: '',
      awsRegion: '',
      signedReadTtlSeconds: null,
      maxAudioBytes: null,
      maxPdfBytes: null,
      maxImageBytes: null,
      maxZipBytes: null,
      maxZipEntries: null,
      maxZipEntryBytes: null,
      maxZipUncompressedBytes: null,
      maxZipCompressionRatio: null,
      chunkSizeBytes: null,
      stagingTtlHours: null,
    },
    pdfExtraction: {
      provider: '',
      azureEndpoint: '',
      azureApiKey: '',
      minTextLengthForSuccess: null,
    },
    pronunciation: {
      provider: '',
      azureSpeechRegion: '',
      azureLocale: '',
      whisperBaseUrl: '',
      whisperModel: '',
      geminiBaseUrl: '',
      geminiModel: '',
      maxAudioBytes: null,
      audioRetentionDays: null,
      freeTierWeeklyAttemptLimit: null,
      freeTierWindowDays: null,
    },
    authTokens: {
      accessTokenLifetimeSeconds: null,
      refreshTokenLifetimeSeconds: null,
      otpLifetimeSeconds: null,
      authenticatorIssuer: '',
    },
    webPush: {
      enabled: null,
    },
    support: {
      whatsAppNumber: '',
      whatsAppProofTemplate: '',
      isWhatsAppConfigured: false,
    },
    firebaseOtp: {
      enabled: false,
      smsEnabled: true,
      emailLinksEnabled: false,
      fallbackToBrevo: true,
      projectId: '',
      authDomain: '',
      webApiKey: '',
      isSmsConfigured: false,
    },
    security: {
      singleActiveSessionEnabled: null,
      riskMode: 'off',
      trustedDeviceRequired: null,
      deviceChangeWindowDays: null,
      deviceChangeMaxPerWindow: null,
      inactiveSessionTimeoutDays: null,
      requireVerifiedEmailForLearners: null,
      countryAllowList: '',
      countryAllowListMode: 'off',
      deviceVerificationExemptEmails: '',
      ipIntelligenceProvider: 'off',
      ipinfoToken: '',
      ipIntelligenceConfigured: false,
    },
    videoProtection: {
      revokeOnCaptureDetected: null,
      blockRootedDevices: null,
      blockEmulators: null,
    },
    updatedBy: null,
    updatedByUserId: null,
    updatedAt: null,
  };
}
