namespace OetLearner.Api.Services.Rulebook;

/// <summary>
/// Single source of the owner's Writing rule wording — Writing Rule
/// Enforcement Addendum Revisions 7-8 (11 Sep 2026), the Writing Master
/// Specification "ULTIMATE FINAL" handoff (13 Sep 2026), the FINAL WRITING
/// OWNER CLARIFICATIONS ADDENDUM (14 Sep 2026, rules OA-01..OA-15) and
/// ADDENDUM TWO (14 Sep 2026, rules OA2-01..OA2-20), the owner clarification
/// rounds OA3/OA4 and the Senior Assessor Release Audit (16 Sep 2026, OA5,
/// rules 24-39 below) — rendered into every
/// consumer so the Model Answer generator, the independent Model Answer
/// validator and the candidate grader receive the SAME applicable rules, with
/// only the strictness differing by lane.
/// Registry rows OWN-W-001..OWN-W-038 + OA-01..OA-15 + OA2-01..OA2-20
/// (docs/canonical-rules/OET_AI_Rules_Master.jsonl) carry the same content;
/// <see cref="WritingRuleEngine"/> enforces every machine-checkable rule
/// deterministically; <see cref="WritingRuleProvenance"/> carries each
/// rule's authority tag and candidate behaviour.
/// </summary>
public static class WritingRev8HouseStyle
{
    public const string Version = "cross-model-audit-2026-09-17";

    /// <summary>
    /// Stricter canonical house style for GENERATED Model Answers. Every item is
    /// mandatory; a Model Answer may be stored/published only with zero
    /// violations.
    /// </summary>
    public const string ModelAnswerCanonicalRules = """
        OWNER WRITING RULES — SENIOR ASSESSOR RELEASE AUDIT (16 Sep 2026, OA5) ON TOP OF OWNER CLARIFICATIONS ADDENDUM TWO (14 Sep 2026, OA2-01..OA2-20), ADDENDUM ONE (OA-01..OA-15) + ULTIMATE FINAL — MANDATORY FOR EVERY GENERATED MODEL ANSWER
        Source fidelity outranks every stylistic rule
        0a. A catalogue code, template, validator regex or house preference NEVER invents admission, discharge, diagnosis, certainty, dates, treatment, requested action, patient identity or clinical interpretation (OA2 source-facts control). The exact canonical case notes + the exact Writing Task decide WHAT happened; these rules decide only HOW a supported fact is written. If the notes record no date of birth and no age, the Re: line carries the name alone — never an invented DOB.
        Letter-type classification (source fidelity)
        0. Determine the FUNCTIONAL letter type from BOTH the case notes and the exact Writing Task — never from a catalogue code alone (OA-05, OA2-02). Hospital admission AND discharge/return to ongoing care proven in the notes = update-on-discharge (say so: admission/treatment context, discharge/return, ongoing-care request). No supported admission/discharge = SIMPLE UPDATE: "presented with" is correct, and you never invent "ready for discharge", "being discharged", "was admitted", discharge medications or transfer of care. Never infer admission from treatment intensity or from an LT-DG label. Care/responsibility moving to another service = transfer (continuity actions explicit). Suspected cancer alone does NOT make a referral urgent. If the task does not confidently fit a defined type, treat it as Other Letters and build from task function.
        Layout and spacing
        1. Recipient name/address block copied from the task with EACH COMPONENT ON ITS OWN LINE (never slash- or comma-joined — convert source commas/slashes to line breaks and preserve exact content), one blank line, the date, one blank line, then "Dear ...," with the "Re:" line on the very next line (the salutation and Re must never share a physical line), one blank line, then the introduction (OA-11: never "Elsternwick, Vic 3185" on one line, never improvised prose metadata).
        2. Exactly one blank line after the Re: line, one blank line between every paragraph (each paragraph is one block, no line breaks inside it), one blank line before "Yours sincerely,"/"Yours faithfully," and one blank line before the professional designation.
        3. "Yours sincerely," when the recipient is named. "Yours faithfully," when the recipient is genuinely unnamed — and a ROLE is not a name, so a letter addressed to "Dear Admissions Officer," still closes "Yours faithfully,". After the closing phrase write ONLY the professional designation (Doctor, Nurse, Registered Nurse, Pharmacist, Physiotherapist, Dentist, Dietitian, Occupational Therapist, Optometrist, Podiatrist, Radiographer, Speech Pathologist) unless the task supplies the exact writer name. Never add a hospital, department, address, phone or email beneath it.
        4. No round, square or curly brackets and no placeholders anywhere. No contractions.
        Salutation (OA2-17)
        4a. When the task gives a named ROLE but no person name, the salutation uses that exact role: "The Admissions Officer" -> "Dear Admissions Officer,". NEVER substitute a synonym ("Dear Admitting Officer,") and never fall back to "Dear Sir/Madam," when a usable role is supplied. Rule-book special salutations such as Emergency Registrar remain role-based. "Dear Sir/Madam," stays acceptable only when no usable name or role exists.
        Re: line, dates, age and DOB
        5. Re: line carries the patient's FULL source-supported identification (OA-03, OA2-04): adult = title + first + last name (e.g. "Re: Mr Allen Mathis, aged 61" when the source gives an age and no DOB, or "Re: Mrs Betty Weston, DOB: 12 February 1964"); child (0-17) = first + last name with no title, never "Master". Write "DOB:" with a colon. Never write "DOB not provided" — and never write a date of birth or an age the case notes do not record. DOB HAS PRIORITY OVER AGE (OA3-03): when the case notes supply a DOB, the Re: line uses it ("Re: Mr John Smith, DOB: 1 January 1980"), never "aged X"; "aged X" is only for a source with no DOB. The patient's name is copied with the EXACT source spelling (OA3-02) — one missing or extra letter is a source-fidelity error.
        6. Use ONE date-format family in the whole letter (fully written "13 June 2020" is preferred) and always a four-digit year. The letter date is NEVER invented: it is the source-supported date of treatment — never a date later than the last date documented in the case notes (OA-01 source fidelity). Never write today's exact date in the body; write "today" alone (never "on today", "at review on today", "of today" or "By today"), and an EARLIER visit keeps its own source date. Never write "yesterday"; write "one day prior". Use "on the following visit" / "later on", never "next visit".
        7. If the age is in the Re: line, do not repeat it in the introduction.
        Introduction and closure
        8. Introductory time and examination phrases take a comma (OA4-02): "Today, ...", "On examination, ...", "On 12 June 2026, ...", "Initially, ...". The introduction MUST begin with "I am writing to ..." (OA-02) and IMMEDIATELY state the exact task-specific purpose (OA-01, OA2-03): "I am writing to update you regarding Ms Isabel Garcia's treatment for bacterial meningitis and request follow-up of her close contacts." or "I am writing to request your occupational therapy assessment and management of Mrs Betty Weston, who has been diagnosed with carpal tunnel syndrome." Never a vague hand-off ("given a working assessment of possible ..."). If the task requires reader action, that action is clear in the opening OR reserved as the specific closure request — never buried in a body paragraph. If the task is a pure information/update task that explicitly requests no action, state the informational purpose precisely and DO NOT invent a request to satisfy a template (OA2-03).
        8a. The full patient name may appear ONCE in the introduction when it is syntactically part of the purpose clause ("regarding Ms Isabel Garcia", "on Ms Isabel Garcia", "of Mrs Betty Weston"); every later adult reference returns to title + surname (OA2-04).
        9. Closure paragraphing is STRUCTURAL (OA-06, OA2-05, OA2-06): the task-specific request ("I would be grateful if you could ...") forms its OWN paragraph and STARTS with the request sentence. The universal contact-offer sentence is a SEPARATE FINAL paragraph immediately before the sign-off, and the canonical form is "Should there be any queries, kindly do not hesitate to contact me." Never append "with any queries" to a fixed contact template that already carries the meaning (OA2-19). The closure never mechanically repeats the introduction's request: opening = primary purpose; closure = a DISTINCT remaining action supported by the task (e.g. MRI consideration, confirmation of admission).
        10. URGENT referral: make urgency explicit in the introduction ("I am writing to request your urgent rheumatological assessment and management of Mr Taylor, who has presented with ..."); use the word "urgent/urgently" ONLY in the introduction; the closure request contains "at your earliest convenience", and the contact offer follows as the separate final paragraph (OA-06). Never write "ASAP".
        11. The closure only closes the letter: no management, advice or history after the closing request. Avoid "consider possible X" — write a direct but appropriately qualified request ("consider tophus removal, if clinically indicated"). If a follow-up/review date is stated in the notes and relevant, include it; if the task states results/imaging are enclosed, mention the enclosure; preserve documented patient-initiated referral/consent accurately.
        Patient reference
        12. After the Re: line, adults = title + surname ("Mr Taylor"), children = first name. TITLE FIDELITY (OA4-03): the patient's title is fixed by the source and the Re: line — a Mrs patient is never Ms in the body, and vice versa. The INTRODUCTION may use EITHER title + surname ("Mr Weir") OR the full patient name ("Mr Michael Weir") — both are correct (OA3-01); after the introduction the body uses title + surname only.
        13. Start EVERY paragraph after the introduction whose content concerns the patient with the approved name form at the first mention (OA-14), then use he/she/his/her later in that same paragraph. Never begin a body paragraph with He/She/His/Her.
        14. Never write "the patient", "this patient" or "a patient at this practice". When the patient is named, never use "your mother"/"your father"/another relationship label as the patient reference.
        Organisation
        15. Background placement is a STRICT canonical rule (OA2-12). If medical history, family history, social history, smoking/drinking or other special habits are relevant enough to include at all, they go in a DEDICATED background paragraph immediately before the closure — never mixed into the opening current-problem paragraph. Do NOT force irrelevant background in merely to create that paragraph, and letter-type exclusions still apply: a GP discharge/update omits history the GP already knows unless it materially affects care.
        16. Urgent referral: body paragraph 1 is today's / the current acute presentation ONLY (keep it as its own paragraph even if brief); then return to relevant earlier history in chronological order; for a hospital urgent referral mention every ongoing condition for which the person takes active medication, with that medication and dose.
        17. Body (introduction to closure inclusive) is 180-200 words; one clear function per paragraph — current problem, progression, management/response, background, then the closure request and the contact offer. Select content by what changes the recipient's understanding, safety, continuity or requested action (OA2-13): never include a fact just because it is medically interesting, and never drop a functional or safety fact merely to reach the word count.
        Reader
        17a. Allied-health recipients are HEALTHCARE PROFESSIONALS, not lay readers (OA2-18). An occupational therapist, physiotherapist, pharmacist or radiographer understands diabetes mellitus, hypothyroidism and arthritis/arthrosis, so never translate common clinical diagnoses into lay language for them. Apply reader relevance instead: include only the diagnoses and details that bear on their functional/safety/therapy role, and avoid unnecessary specialist jargon and irrelevant laboratory detail.
        Language
        18. Descriptive/general numbers in words ("every six hours for four days", "two weeks ago", "three children", "twenty cigarettes daily", "a forty-eight-hour ketamine infusion"; "type two diabetes mellitus" — OA-12, OA2-15); digits only for identification ages ("aged 61", "a 20-year-old"), dates, vital signs, investigation/lab values, medication doses and clinical measurements ("20 July 2018", "88/70 mmHg", "2 g", "32 kg/m²"); an age at a past event is descriptive ("had an appendectomy at age fifteen") and ranges are never mixed ("thirty to thirty-five cigarettes daily").
        19. Medication syntax (OA2-16, LATEST owner override): one item = "Drug, dose"; two = "Drug, dose and Drug, dose"; three or more = semicolons BETWEEN the medication-dose pairs with NO semicolon before the final "and" — "Zyloric, 300 mg daily; Lipitor, 20 mg at night; Karvina, 300 mg daily and Nicabate patch, 21 mg." This SUPERSEDES the older "; and final drug" house syntax. Dose ranges and combination strengths ("5-10 mg", "20/10") are written source-faithfully and never rewritten to suit a parser. Always a space between value and unit ("500 mg", "2 g", "6.37 mmol/L", "37.8 °C", "90 bpm", "120/80 mmHg" — OA-15); respiratory rate is "22 breaths/min", never "22 /min". Translate Latin abbreviations (twice a day, at night). Capitalise trade names, generic names lowercase. Never invent a dose, route or frequency. Name one clear source-supported medication identity — do not repeat a "generic, also known as Brand" pairing in paragraph after paragraph. Reader-appropriate abbreviations (MRI) stay abbreviated; never "MRI imaging" (OA-13).
        20. No emotional or editorial words (suffer/suffered, unfortunately, regrettably, sadly). No judgmental labels or emotional observations ("appeared anxious"): write precise neutral findings; a clinically documented anxiety DIAGNOSIS may be stated factually. Restore quantities exactly: never "drinking over six to ten standard drinks daily" — "six to ten standard drinks daily". Never "has been overweight long term" — "has long been overweight"; do not label a person "a smoker" when the notes support "continues to smoke".
        21. Linkers: do NOT use but, so, hence, furthermore or moreover, and do not use "also" as a LINKING device (an adverbial "also" inside a clause — "kidney stones were also noted that year" — is correct English and is fine). Use however / therefore / thus / consequently / subsequently / in addition only where logically needed, with "However, ..." at a sentence start.
        21a. Sentence architecture (OA2-07): prefer ONE main clinical action per sentence, or two closely related clauses joined cleanly with "and" when the subject relationship is clear. When the subject or the action changes, start a new sentence. No comma splices. AVOID SEMICOLONS IN ORDINARY NARRATIVE PROSE ENTIRELY — a canonical Model Answer uses a full stop or a normal conjunction, never "...twice daily; dexamethasone was continued..." and never "...in 2010; kidney stones were noted that year." Medication-list separators (rule 19) are the one exception. Do not chain three or four separate clinical actions into one sentence to save words.
        22. Voice and grammar (OA-09, OA2-09): complete passive forms — "dexamethasone was continued six-hourly", "treatment was changed to benzylpenicillin", never "dexamethasone continued ..." / "treatment changed to ...". "On examination, Ms Garcia was afebrile ...", never "Examination showed afebrile". "bruising on the left arm", not "bruising to her left arm". Positional wording is "when supine", "while supine", "when lying supine" or "in the supine position" — NEVER "on supine position" (OA2-10). A treatment clause never dangles on a specimen (OA3-05): "A catheter urine culture grew Staphylococcus saprophyticus, and Mr McDonald was treated with Keflex for five days.", never "..., treated with five days of Keflex".
        22a. Investigation and vital-sign grammar (OA2-08, OA2-11, OA3-04 LATEST): canonical Model Answers state result values with the owner's "at" construction on a COMPLETE result noun — "a white cell count at 1,000", "a reduced glucose level at 10 mg/dL", "an elevated protein level at 70 mg/dL", "the cholesterol level at 6.37 mmol/L", "the C-reactive protein level was/was recorded at 150". Headless values ("reduced glucose 10 mg/dL") and "of" forms ("a white cell count of 1000") are REJECTED, as are fragments like "1000 white cells" when the datum is a count. Never invent a unit the source does not supply. Coordinate two result clauses with "and" or split them into short sentences; never comma-splice them.
        23. Use only facts present in the case notes; preserve every clinical fact, laterality, anatomical site, dose, unit, date, trend and certainty level exactly (a prophylactic intention is never upgraded to a guarantee; a suspicion is never upgraded to a confirmed diagnosis). A relevant abnormal vital sign is reported as its RAW value and unit and is never labelled with a diagnosis the notes did not state — write "the blood pressure was 88/70 mmHg", not "hypotension" (OA2-14). Name vague objects exactly ("possible tophus removal", never bare "possible removal"). Copy the recipient's name EXACTLY as the task spells it — the task spelling controls in both directions.
        Senior Assessor Release Audit (16 Sep 2026, OA5) — Model Answer rules
        24. Every sentence has its own subject and finite verb: never a verbless or subjectless sentence ("With poorly controlled diabetes, hypertension and ischaemic heart disease.", "However, no effusion.", "Lives with her long-term boyfriend, ...", "However, was initially resistant ...", "And prescribed eflornithine cream ..."), and never split a phrase ("At your earliest convenience.") or a medication item into its own sentence (sentence_fragment).
        25. Every coordinated passive clause carries its own auxiliary ("The Department of Human Services was notified, and family immunisation was discussed.", "..., and atorvastatin, 20 mg daily, was added."), and a "with" list stays parallel ("with a petechial rash on the abdomen and legs, bruising on the left arm and inability to touch her chin to her chest when supine" or "..., and was unable to touch ..."), never "... and unable to touch ..." (incomplete_clinical_construction).
        26. No mechanical find-and-replace damage: no malformed word form ("an ex-smokes", "has been continued smoking", "social drinks alcohol" — write "smoked for thirty-five years and quit seven years ago", "has continued smoking", "drinks alcohol socially"), no doubled word ("diabetes mellitus mellitus"; "had had" is valid), no space before punctuation ("medial aspect ."), and every sentence starts with a capital letter (malformed_word_form, typographic_corruption). "today" is an adverb: "presented today", "At today's review, ...", never "presented on today", "At review on today", "since today", "by her last period of today" or a sentence opening "By today" (malformed_today_phrase).
        27. A patient name that owns the following noun takes the possessive: "Mrs Clarke's temperature", "Mrs MacIntyre's history", "Ms Johnson's right total knee replacement" (or "her temperature"), never "Mrs Clarke temperature" (missing_possessive_name).
        28. Every introductory time, date or examination phrase takes a comma whatever follows it: "On examination, she ...", "On admission, ...", "On discharge, ...", "The following morning, ...", "Overnight, ...", "Over the past three weeks, ...", "On 23 November 2019, ...", "In August 2019, ...", "At review on 25 August, ..." (intro_adverbial_comma).
        29. Numbers, units and names: descriptive quantities are words and never mixed forms ("thirty to thirty-five cigarettes daily", never "30 to thirty-five" or "5-six"; "forty units of alcohol weekly"; "less than fifteen minutes"; "thirty days off work"; an age at a past event "at age fifteen"). Times are "8 am" / "3 pm" (never "8am"); squared or cubed units use superscripts ("kg/m²", "per mm³"). Every vital sign carries its unit directly after the value: blood pressure "148/98 mmHg", pulse or heart rate "96 bpm", respiratory rate "16 breaths/min", temperature "37.8 °C". Generic medicine names are lowercase in running text ("indomethacin", "colchicine", "frusemide"); only trade names are capitalised.
        30. Patient identity is proven against the source: the DOB-derived age at the letter date is the truth — a stated age never contradicts the DOB, and a notes-stated age that contradicts it is never copied (omit the age) (age_dob_inconsistent). Minor status is decided by the DOB at the letter date (0-17 is a child): a child's Re: line has the full name with no title and the body uses the first name, never title + surname (minor_naming_convention). An adult is never called by the first name alone ("Erika fasting sugars") (body_uses_last_name_only). The Re: line title agrees with the letter's pronouns ("Re: Mr ..." with only she/her pronouns is an identity error) (patient_title_mismatch). A notes sentence "<patient> was born on <date>" is a DOB, so the Re: line carries "DOB: <date>" (re_line_dob_priority).
        31. When the case notes state the patient's age and record NO date of birth (no DOB, date of birth or "born on" entry), the Re: line ends ", aged N" with that exact number ("Re: Mr Allen Mathis, aged 61"), never the name alone; relatives' ages, past-event ages and ages in months never supply N (re_line_age_when_no_dob).
        32. The recipient block contains ONLY the recipient content the Writing Task (or the case notes) supplies, one component per line: never invent a recipient name, department, clinic or street ("a neuro-ophthalmologist" gives "Neuro-Ophthalmologist", never "Dr Helena Rao / City Eye Centre / 45 Bridge Street"); never drop the task's recipient name, post-nominals ("Dr Anne Childers MBBS FRANZCOG") or postcode ("NW1 2TG"); keep the task's own spelling ("Wooloongabba") (address_content_unsupported). A role recipient written without "The" is still a role: "Gynaecology Registrar" takes "Dear Gynaecology Registrar,", never "Dear Doctor," (role_salutation_matches_task).
        33. The sign-off is "Yours sincerely," or "Yours faithfully," alone on its line, one blank line, then ONE designation line, and nothing after it; never "Yours sincerely, Doctor" and never a repeated designation (signoff_designation_present).
        34. Letter type follows the task function, never the catalogue code: case notes carrying an urgent plan (urgent referral/assessment/admission/surgical opinion, needs or requires admission, admission for stabilisation, send to hospital) or a task letter addressed to an emergency role (Emergency Registrar, Emergency Department, ED Medical Officer, A&E, Admitting Officer, Duty Registrar) make the letter an URGENT referral written to the urgent contract; suspected cancer alone never does (letter_type_function_mismatch).
        35. Closure request: the paragraph immediately before the contact offer is the request paragraph and STARTS with "I would be grateful if you could ..." (or "I would be grateful for ..." / "I would appreciate ...", optionally after one introductory adverbial); never "Please monitor/review/see ...", never a request merged into a clinical sentence, and never no request unless the task explicitly requests no action (closure_request_paragraph). Its action is DISTINCT from the introduction's request: no second assessment + management/advice request, no second admission or biopsy request, no repeated request object and no bare "assess and advise" closure (no_duplicated_request). A discharge (or "I am writing to introduce ...") introduction states the ongoing-care request ("... and to request your ongoing monitoring of ..."); "admission" is never a reader action (intro_purpose_vague).
        36. Background (medical, social, habit, family and allergy details) never opens a body paragraph that comes before current-episode content and is never mixed into a paragraph with today's presentation, examination, diagnosis or management; it lives only in the dedicated paragraph immediately before the closure (background_paragraph_placement).
        37. Register: no emotional or affective observations ("is/was anxious", "anxious and worried", "quite worried", "in distress", "no obvious anxiety", "bored", "feels discouraged", "embarrassing") unless the referred condition is psychiatric or psychological and the wording is a clinical finding ("symptoms of anxiety"); "suspected X" or "possible X", never "query X" or "?X"; "fatigue", never "tiredness"; never "confirm the working diagnosis of possible X" and never "A viral infection was assessed"; never "per this referral" or a specialist noun as a modifier ("dermatological review", not "dermatologist review") (register_colloquial). Neutral behaviour wording: "adherence", never "compliance"/"non-compliance"; "did not attend", never "defaulted"; the objective observations, never "bizarre behaviour"; the exact quantity and frequency, never "drinks heavily" (judgmental_labels).
        38. Medication syntax extensions: weight-based doses ("isoniazid, 5 mg/kg daily") and alphanumeric brands ("NovoMix30, 25 units") follow rule 19 exactly; a formulation belongs with the medicine name ("salbutamol nebules, 5 mg", never "Salbutamol, 5 mg, nebules") (medication_list_punctuation); one coherent frequency per medicine — never "5 mg twice daily each morning" (medication_frequency_conflict).
        39. Chronology and required facts: the letter date is the source's today — when the case notes, the task or the scenario state today's date the letter carries exactly that date; otherwise it is never earlier than the latest documented encounter and never later than every documented date, reading numeric note dates (21/03/15, 17.06.2018) exactly like written ones; appointments, planned or due dates and the LMP never count (letter_date_unsupported). The narrated chronology must be possible on the letter date: never a past event dated after the letter date, never "hurt his back on today and presented four days later", never "her last period of today" (narrated_chronology_contradiction). Owner-required facts are never dropped: when the case notes record Mr Michael Weir's blood pressure of 88/70, the letter states "His blood pressure was 88/70 mmHg." (owner_required_fact_missing).
        Cross-model audit (17 Sep 2026, OA6) — Model Answer rules
        40. HARD GLOBAL RULE (OA6-01): the same functional request never appears in both the introduction and the closure, in ANY wording. The introduction carries the primary request; the closure carries one DISTINCT, source-supported next step. Reworded repeats fail: "request follow-up of close contacts" then "contact close family and friends"; "request your ongoing care pending outpatient endocrinological review" then "monitor her until her endocrinologist's appointment"; "for regular wound dressing" then "for dressing changes"; "request your psychiatric assessment" then "confirm the diagnosis" (no_duplicated_request). "Clarify/establish the possible diagnosis" and a distinct investigation ("arrange bronchoscopy and biopsy") remain correct.
        41. The closure requests only what the case notes plan (OA6-02): never ask the reader to monitor, check, repeat or test a clinical parameter (electrolytes, blood pressure, INR, glucose, symptoms, medications ...) unless a case-note line plans that monitoring, however clinically reasonable it sounds — Sylvia Meadows "monitor Mrs Meadows's symptoms and electrolytes" was invented (request_action_unsupported).
        """;

    /// <summary>
    /// The same owner rules as they apply to CANDIDATE grading: descriptor-first,
    /// source-grounded and fair. Professional alternatives and semantic
    /// equivalents are accepted; Model Answer wording is never required; and the
    /// complete false-positive firewall (Ultimate Final §17, OA2-20) below is
    /// non-negotiable.
    /// </summary>
    public const string CandidateGradingRules = """
        OWNER WRITING RULES — ADDENDUM TWO (14 Sep 2026) — CANDIDATE GRADING
        Two lanes. Grade the candidate from the case notes + exact task + the six official criteria + validated English. The Model Answer's house style is NOT the candidate's standard: a house-style deviation is coaching feedback unless an independent OET criterion (clarity, accuracy, register, cohesion, safety, professionalism) is genuinely affected. OA2-20 is explicit — the strict canonical requirements added by Addendum Two (background paragraph position, narrative-semicolon avoidance, the exact contact template, "type two", the house medication separator, the preferred salutation) must be kept OUT of candidate scoring unless an actual official criterion impact exists.

        Letter-type classification — derive the functional type from the case notes + exact task, never from a stored code alone. Do NOT force a discharge template when the notes do not support admission/discharge; do NOT invent "ready for discharge" facts. Suspected cancer alone is not automatic urgency — assess whether the task/notes actually support urgent action. A routine cancer-screening task is not urgent.

        CANDIDATE FALSE-POSITIVE FIREWALL — these professional alternatives must NOT be penalised:
        1. Any professional opening whose purpose/action is immediately clear ("I am writing to ..." is a Model-Answer house form only).
        2. More than four body paragraphs — no count-only penalty; assess organisation/readability.
        3. Word count slightly outside 180-200 — no fixed arithmetic deduction; assess relevance, omission and excess.
        4. Correct use of "but"/"so"/"also" — standard-correct English is never a grammar error; style feedback only unless real cohesion/register weakness exists.
        5. No universal contact-offer sentence — another professional, task-complete closure can pass fully.
        6. Urgent closure without "at your earliest convenience" — any clear professional urgency is acceptable; repeating "urgent/urgently" is not automatically penalised.
        7. A different clear, grammatically sound medication list (the exact house comma/semicolon form is not a universal template; ambiguity, grammar or safety impact is what scores).
        8. A descriptive number written as a digit — no fixed penalty unless standard usage, clarity or register is actually harmed.
        9. A pronoun-first paragraph with a clear referent; and natural use of "the patient" — flag only real ambiguity, repetition or impersonal-tone impact.
        10. An alternate clear DOB/patient-identification form — score genuine identification/professionalism problems, not template mismatch.
        11. Brackets/parentheses — not automatically wrong; assess readability/register impact.
        12. Familiar, profession-appropriate abbreviations the intended reader would understand.
        13. A clinically correct paraphrase/synonym, however far from Model Answer wording — Model Answer similarity contributes ZERO to the score.
        14. A different coherent paragraph order when task needs, clinical chronology and reader action remain clear.
        15. A clinically documented anxiety (or similar) diagnosis stated factually — a diagnosis is not a judgemental label.
        16. "type 2 diabetes mellitus" written with the digit — Model Answers use "type two" (OA-12); a candidate is never penalised for the digit.
        17. A clear professional opening other than "I am writing to ..." (OA-01/OA-02): Purpose is assessed semantically, never by template wording.
        18. The full patient name once in the introduction's purpose clause ("regarding Ms Isabel Garcia") — clear professional naming variations are accepted when clarity and cohesion are intact (OA-03/OA2-04).
        19. Different closure paragraphing or a closure request phrased differently from the Model Answer — house paragraphing is not imposed on candidates (OA-06/OA-07): duplication is judged semantically, never by phrase matching.
        20. Background placed somewhere other than a dedicated paragraph immediately before the closure (OA2-12) — assess logical organisation and relevance; the exact house paragraph position is never required of a candidate.
        21. A grammatically correct semicolon joining two related clauses (OA2-07) — narrative-semicolon avoidance is canonical Model Answer style; for a candidate judge clarity and sentence control, never the punctuation mark itself.
        22. Any professional semantic equivalent of the contact offer (OA2-19) — never score the contact sentence by exact phrase matching.
        23. A different but clear professional salutation where official task conventions permit it (OA2-17) — score a genuinely wrong or invented recipient, not a defensible alternative form.
        24. Common clinical diagnosis terms addressed to an allied-health reader (OA2-18): diabetes mellitus, hypothyroidism and arthritis/arthrosis are NOT "too medical" for an occupational therapist, physiotherapist, pharmacist or radiographer. Judge reader relevance — irrelevant specialist detail can still cost marks; correct professional terminology never does.
        25. A natural result construction that differs from the canonical "at" form (OA3-04) — "the white cell count was ...", "a white cell count of ...", "the temperature was ...", "a temperature of ..." are all correct FOR CANDIDATES; the "at" house wording is canonical only for Model Answers. Never penalise a candidate's grammatical, source-faithful result grammar.
        26. The Senior Assessor Release Audit house forms (16 Sep 2026, OA5) are Model-Answer canon, never candidate templates: "tiredness" instead of "fatigue", "compliance" instead of "adherence", a short introductory phrase without a comma, a descriptive number, a past-event age or a clock time written with digits ("8am"), "kg/m2", a capitalised generic medicine name, a request paragraph that opens "Please ...", a closure that restates the introduction's request in other words, background placed in another logical paragraph, a Re: line without "aged N", a recipient block formatted differently from the task, or a role salutation other than the exact role — none of these is a candidate penalty unless an official criterion is genuinely affected.
        27. The cross-model audit detectors (17 Sep 2026, OA6: the request-concept duplicate branch and request_action_unsupported) run for Model Answers only. A candidate closure that restates the introduction's request, or asks for monitoring the notes do not plan, is judged by the grader against the official criteria and is never penalised by these detectors.

        ALWAYS score as genuine errors: invented facts/dates/doses/diagnoses/admissions/discharges/patient identity; upgraded certainty (suspected -> confirmed, prophylaxis -> guarantee); an interpretation the notes never made (calling 88/70 mmHg "hypotension"); important omissions the recipient needs; wrong recipient/task action; delayed or vague purpose; tense changes that alter the timeline; grammar/punctuation/spelling errors; comma splices and incomplete constructions (e.g. "examination showed afebrile", "1000 white cells" where a count is meant, "on supine position"); mixed date families or abbreviated years; collapsed layout that harms professional readability; emotional/judgemental wording; colloquial register where a professional equivalent exists; unsafe unexplained shorthand; clinical values without units or with missing unit spaces; medication errors that affect clarity or safety.

        Clean answers stay clean: never manufacture a finding to fill a feedback template. Every finding must state the exact quote, the OET criterion it affects, why it matters for the reader, and a corrected wording.
        """;
}
