namespace OetLearner.Api.Services.Rulebook;

/// <summary>
/// Single source of the owner's Writing rule wording — Writing Rule
/// Enforcement Addendum Revisions 7-8 (11 Sep 2026), the Writing Master
/// Specification "ULTIMATE FINAL" handoff (13 Sep 2026), the FINAL WRITING
/// OWNER CLARIFICATIONS ADDENDUM (14 Sep 2026, rules OA-01..OA-15) and
/// ADDENDUM TWO (14 Sep 2026, rules OA2-01..OA2-20) — rendered into every
/// consumer so the Model Answer generator, the independent Model Answer
/// validator and the candidate grader receive the SAME applicable rules, with
/// only the strictness differing by lane.
/// Registry rows OWN-W-001..OWN-W-038 + OA-01..OA-15 + OA2-01..OA2-20
/// (docs/canonical-rules/OET_AI_Rules_Master.jsonl) carry the same content;
/// <see cref="WritingRuleEngine"/> enforces every machine-checkable rule
/// deterministically; <see cref="WritingRuleProvenance"/> carries each
/// rule's authority tag and candidate behaviour.
/// </summary>
public static class WritingRev8HouseStyle
{
    public const string Version = "owner-clarifications-3-2026-09-16";

    /// <summary>
    /// Stricter canonical house style for GENERATED Model Answers. Every item is
    /// mandatory; a Model Answer may be stored/published only with zero
    /// violations.
    /// </summary>
    public const string ModelAnswerCanonicalRules = """
        OWNER WRITING RULES — OWNER CLARIFICATIONS ADDENDUM TWO (14 Sep 2026, OA2-01..OA2-20) ON TOP OF ADDENDUM ONE (OA-01..OA-15) + ULTIMATE FINAL — MANDATORY FOR EVERY GENERATED MODEL ANSWER
        Source fidelity outranks every stylistic rule
        0a. A catalogue code, template, validator regex or house preference NEVER invents admission, discharge, diagnosis, certainty, dates, treatment, requested action, patient identity or clinical interpretation (OA2 source-facts control). The exact canonical case notes + the exact Writing Task decide WHAT happened; these rules decide only HOW a supported fact is written. If the notes record no date of birth and no age, the Re: line carries the name alone — never an invented DOB.
        Letter-type classification (source fidelity)
        0. Determine the FUNCTIONAL letter type from BOTH the case notes and the exact Writing Task — never from a catalogue code alone (OA-05, OA2-02). Hospital admission AND discharge/return to ongoing care proven in the notes = update-on-discharge (say so: admission/treatment context, discharge/return, ongoing-care request). No supported admission/discharge = SIMPLE UPDATE: "presented with" is correct, and you never invent "ready for discharge", "being discharged", "was admitted", discharge medications or transfer of care. Never infer admission from treatment intensity or from an LT-DG label. Care/responsibility moving to another service = transfer (continuity actions explicit). Suspected cancer alone does NOT make a referral urgent. If the task does not confidently fit a defined type, treat it as Other Letters and build from task function.
        Layout and spacing
        1. Recipient name/address block copied from the task with EACH COMPONENT ON ITS OWN LINE (never slash- or comma-joined — convert source commas/slashes to line breaks and preserve exact content), one blank line, the date, one blank line, then "Dear ...," with the "Re:" line on the very next line (the salutation and Re must never share a physical line), one blank line, then the introduction. (OA-11: never "Elsternwick, Vic 3185" on one line, never improvised prose metadata), one blank line, the date, one blank line, then "Dear ...," with the "Re:" line on the very next line.
        2. Exactly one blank line after the Re: line, one blank line between every paragraph (each paragraph is one block, no line breaks inside it), one blank line before "Yours sincerely,"/"Yours faithfully," and one blank line before the professional designation.
        3. "Yours sincerely," when the recipient is named. "Yours faithfully," when the recipient is genuinely unnamed — and a ROLE is not a name, so a letter addressed to "Dear Admissions Officer," still closes "Yours faithfully,". After the closing phrase write ONLY the professional designation (Doctor, Nurse, Registered Nurse, Pharmacist, Physiotherapist, Dentist, Dietitian, Occupational Therapist, Optometrist, Podiatrist, Radiographer, Speech Pathologist) unless the task supplies the exact writer name. Never add a hospital, department, address, phone or email beneath it.
        4. No round, square or curly brackets and no placeholders anywhere. No contractions.
        Salutation (OA2-17)
        4a. When the task gives a named ROLE but no person name, the salutation uses that exact role: "The Admissions Officer" -> "Dear Admissions Officer,". NEVER substitute a synonym ("Dear Admitting Officer,") and never fall back to "Dear Sir/Madam," when a usable role is supplied. Rule-book special salutations such as Emergency Registrar remain role-based. "Dear Sir/Madam," stays acceptable only when no usable name or role exists.
        Re: line, dates, age and DOB
        5. Re: line carries the patient's FULL source-supported identification (OA-03, OA2-04): adult = title + first + last name (e.g. "Re: Mr David Taylor, aged 55" or "Re: Mrs Betty Weston, DOB: 12 February 1964"); child (0-17) = first + last name with no title, never "Master". Write "DOB:" with a colon. Never write "DOB not provided" — and never write a date of birth or an age the case notes do not record. DOB HAS PRIORITY OVER AGE (OA3-03): when the case notes supply a DOB, the Re: line uses it ("Re: Mr John Smith, DOB: 1 January 1980"), never "aged X"; "aged X" is only for a source with no DOB. The patient's name is copied with the EXACT source spelling (OA3-02) — one missing or extra letter is a source-fidelity error.
        6. Use ONE date-format family in the whole letter (fully written "13 June 2020" is preferred) and always a four-digit year. The letter date is NEVER invented: it is the source-supported date of treatment — never a date later than the last date documented in the case notes (OA-01 source fidelity). Never write today's exact date in the body; write "today". Never write "yesterday"; write "one day prior". Use "on the following visit" / "later on", never "next visit".
        7. If the age is in the Re: line, do not repeat it in the introduction.
        Introduction and closure
        8. Introductory time and examination phrases take a comma (OA4-02): "Today, ...", "On examination, ...", "On 12 June 2026, ...", "Initially, ...". The introduction MUST begin with "I am writing to ..." (OA-02) and IMMEDIATELY state the exact task-specific purpose (OA-01, OA2-03): "I am writing to update you regarding Ms Isabel Garcia's treatment for bacterial meningitis and request follow-up of her close contacts." or "I am writing to request your occupational therapy assessment and management of Mrs Betty Weston, who has been diagnosed with carpal tunnel syndrome." Never a vague hand-off ("given a working assessment of possible ..."). If the task requires reader action, that action is clear in the opening OR reserved as the specific closure request — never buried in a body paragraph. If the task is a pure information/update task that explicitly requests no action, state the informational purpose precisely and DO NOT invent a request to satisfy a template (OA2-03).
        8a. The full patient name may appear ONCE in the introduction when it is syntactically part of the purpose clause ("regarding Ms Isabel Garcia", "on Ms Isabel Garcia", "of Mrs Betty Weston"); every later adult reference returns to title + surname (OA2-04).
        9. Closure paragraphing is STRUCTURAL (OA-06, OA2-05, OA2-06): the task-specific request ("I would be grateful if you could ...") forms its OWN paragraph and STARTS with the request sentence. The universal contact-offer sentence is a SEPARATE FINAL paragraph immediately before the sign-off, and the canonical form is "Should there be any queries, kindly do not hesitate to contact me." Never append "with any queries" to a fixed contact template that already carries the meaning (OA2-19). The closure never mechanically repeats the introduction's request: opening = primary purpose; closure = a DISTINCT remaining action supported by the task (e.g. MRI consideration, confirmation of admission).
        10. URGENT referral: make urgency explicit in the introduction ("I am writing to request your urgent rheumatological assessment and management of Mr Taylor, who has presented with ..."); use the word "urgent/urgently" ONLY in the introduction; the closure request contains "at your earliest convenience", and the contact offer follows as the separate final paragraph (OA-06). Never write "ASAP".
        11. The closure only closes the letter: no management, advice or history after the closing request. Avoid "consider possible X" — write a direct but appropriately qualified request ("consider tophus removal, if clinically indicated"). If a follow-up/review date is stated in the notes and relevant, include it; if the task states results/imaging are enclosed, mention the enclosure; preserve documented patient-initiated referral/consent accurately.
        Patient reference
        12. After the Re: line, adults = title + surname ("Mr Taylor"), children = first name. TITLE FIDELITY (OA4-03): the patient's title is fixed by the source and the Re: line — a Mrs patient is never Ms in the body, and vice versa. The INTRODUCTION may use EITHER title + surname ("Mr Weir") OR the full patient name ("Mr Michael Weir") — both are correct (OA3-01); after the introduction the body uses title + surname only.
        13. Start EVERY paragraph after the introduction whose content concerns the patient with the approved name form at the first mention (OA-14), then use he/she/his/her later in that same paragraph. Never begin a body paragraph with He/She/His/Her.
        14. Never write "the patient", "this patient" or "a patient at this practice". When the patient is named, never use "your mother"/"your father"/another relationship label as the patient reference.
        Organisation
        15. Background placement is a STRICT canonical rule (OA2-12). If medical history, family history, social history, smoking/drinking or other special habits are relevant enough to include at all, they go in a DEDICATED background paragraph immediately before the closure — never mixed into the opening current-problem paragraph. Do NOT force irrelevant background in merely to create that paragraph, and letter-type exclusions still apply: a GP discharge/update omits history the GP already knows unless it materially affects care.
        16. Urgent referral: body paragraph 1 is today's / the current acute presentation ONLY (keep it as its own paragraph even if brief); then return to relevant earlier history in chronological order; for a hospital urgent referral mention every ongoing condition for which the person takes active medication, with that medication and dose.
        17. Body (introduction to closure inclusive) is 180-200 words; one clear function per paragraph — current problem, progression, management/response, background, then the closure request and the contact offer. Select content by what changes the recipient's understanding, safety, continuity or requested action (OA2-13): never include a fact just because it is medically interesting, and never drop a functional or safety fact merely to reach the word count.
        Reader
        17a. Allied-health recipients are HEALTHCARE PROFESSIONALS, not lay readers (OA2-18). An occupational therapist, physiotherapist, pharmacist or radiographer understands diabetes mellitus, hypothyroidism and arthritis/arthrosis, so never translate common clinical diagnoses into lay language for them. Apply reader relevance instead: include only the diagnoses and details that bear on their functional/safety/therapy role, and avoid unnecessary specialist jargon and irrelevant laboratory detail.
        Language
        18. Descriptive/general numbers in words ("every six hours for four days", "two weeks ago", "three children", "twenty cigarettes daily", "a forty-eight-hour ketamine infusion"; "type two diabetes mellitus" — OA-12, OA2-15); digits only for age, dates, vital signs, investigation/lab values, medication doses and clinical measurements ("20 July 2018", "88/70 mmHg", "2 g", "32 kg/m2").
        19. Medication syntax (OA2-16, LATEST owner override): one item = "Drug, dose"; two = "Drug, dose and Drug, dose"; three or more = semicolons BETWEEN the medication-dose pairs with NO semicolon before the final "and" — "Zyloric, 300 mg daily; Lipitor, 20 mg at night; Karvina, 300 mg daily and Nicabate patch, 21 mg." This SUPERSEDES the older "; and final drug" house syntax. Dose ranges and combination strengths ("5-10 mg", "20/10") are written source-faithfully and never rewritten to suit a parser. Always a space between value and unit ("500 mg", "2 g", "6.37 mmol/L", "37.8 °C", "90 bpm", "120/80 mmHg" — OA-15); respiratory rate is "22 breaths/min", never "22 /min". Translate Latin abbreviations (twice a day, at night). Capitalise trade names, generic names lowercase. Never invent a dose, route or frequency. Name one clear source-supported medication identity — do not repeat a "generic, also known as Brand" pairing in paragraph after paragraph. Reader-appropriate abbreviations (MRI) stay abbreviated; never "MRI imaging" (OA-13).
        20. No emotional or editorial words (suffer/suffered, unfortunately, regrettably, sadly). No judgmental labels or emotional observations ("appeared anxious"): write precise neutral findings; a clinically documented anxiety DIAGNOSIS may be stated factually. Restore quantities exactly: never "drinking over six to ten standard drinks daily" — "six to ten standard drinks daily". Never "has been overweight long term" — "has long been overweight"; do not label a person "a smoker" when the notes support "continues to smoke".
        21. Linkers: do NOT use but, so, hence, furthermore or moreover, and do not use "also" as a LINKING device (an adverbial "also" inside a clause — "kidney stones were also noted that year" — is correct English and is fine). Use however / therefore / thus / consequently / subsequently / in addition only where logically needed, with "However, ..." at a sentence start.
        21a. Sentence architecture (OA2-07): prefer ONE main clinical action per sentence, or two closely related clauses joined cleanly with "and" when the subject relationship is clear. When the subject or the action changes, start a new sentence. No comma splices. AVOID SEMICOLONS IN ORDINARY NARRATIVE PROSE ENTIRELY — a canonical Model Answer uses a full stop or a normal conjunction, never "...twice daily; dexamethasone was continued..." and never "...in 2010; kidney stones were noted that year." Medication-list separators (rule 19) are the one exception. Do not chain three or four separate clinical actions into one sentence to save words.
        22. Voice and grammar (OA-09, OA2-09): complete passive forms — "dexamethasone was continued six-hourly", "treatment was changed to benzylpenicillin", never "dexamethasone continued ..." / "treatment changed to ...". "On examination, Ms Garcia was afebrile ...", never "Examination showed afebrile". "bruising on the left arm", not "bruising to her left arm". Positional wording is "when supine", "while supine", "when lying supine" or "in the supine position" — NEVER "on supine position" (OA2-10). A treatment clause never dangles on a specimen (OA3-05): "A catheter urine culture grew Staphylococcus saprophyticus, and Mr McDonald was treated with Keflex for five days.", never "..., treated with five days of Keflex".
        22a. Investigation and vital-sign grammar (OA2-08, OA2-11, OA3-04 LATEST): canonical Model Answers state result values with the owner's "at" construction on a COMPLETE result noun — "a white cell count at 1,000", "a reduced glucose level at 10 mg/dL", "an elevated protein level at 70 mg/dL", "the cholesterol level at 6.37 mmol/L", "the C-reactive protein level was/was recorded at 150". Headless values ("reduced glucose 10 mg/dL") and "of" forms ("a white cell count of 1000") are REJECTED, as are fragments like "1000 white cells" when the datum is a count. Never invent a unit the source does not supply. Coordinate two result clauses with "and" or split them into short sentences; never comma-splice them.
        23. Use only facts present in the case notes; preserve every clinical fact, laterality, anatomical site, dose, unit, date, trend and certainty level exactly (a prophylactic intention is never upgraded to a guarantee; a suspicion is never upgraded to a confirmed diagnosis). A relevant abnormal vital sign is reported as its RAW value and unit and is never labelled with a diagnosis the notes did not state — write "the blood pressure was 88/70 mmHg", not "hypotension" (OA2-14). Name vague objects exactly ("possible tophus removal", never bare "possible removal"). Copy the recipient's name EXACTLY as the task spells it — the task spelling controls in both directions.
        """;

    /// <summary>
    /// The same owner rules as they apply to CANDIDATE grading: descriptor-first,
    /// source-grounded and fair. Professional alternatives and semantic
    /// equivalents are accepted; Model Answer wording is never required; and the
    /// complete false-positive firewall (Ultimate Final §17, OA2-20) below is
    /// non-negotiable.
    /// </summary>
    public const string CandidateGradingRules = """
        OWNER WRITING RULES — ADDENDUM TWO (14 Sep 2026) — CANDIDATE GRADING
        Two lanes. Grade the candidate from the case notes + exact task + the six official criteria + validated English. The Model Answer's house style is NOT the candidate's standard: a house-style deviation is coaching feedback unless an independent OET criterion (clarity, accuracy, register, cohesion, safety, professionalism) is genuinely affected. OA2-20 is explicit — the strict canonical requirements added by Addendum Two (background paragraph position, narrative-semicolon avoidance, the exact contact template, "type two", the house medication separator, the preferred salutation) must be kept OUT of candidate scoring unless an actual official criterion impact exists.

        Letter-type classification — derive the functional type from the case notes + exact task, never from a stored code alone. Do NOT force a discharge template when the notes do not support admission/discharge; do NOT invent "ready for discharge" facts. Suspected cancer alone is not automatic urgency — assess whether the task/notes actually support urgent action. A routine cancer-screening task is not urgent.

        CANDIDATE FALSE-POSITIVE FIREWALL — these professional alternatives must NOT be penalised:
        1. Any professional opening whose purpose/action is immediately clear ("I am writing to ..." is a Model-Answer house form only).
        2. More than four body paragraphs — no count-only penalty; assess organisation/readability.
        3. Word count slightly outside 180-200 — no fixed arithmetic deduction; assess relevance, omission and excess.
        4. Correct use of "but"/"so"/"also" — standard-correct English is never a grammar error; style feedback only unless real cohesion/register weakness exists.
        5. No universal contact-offer sentence — another professional, task-complete closure can pass fully.
        6. Urgent closure without "at your earliest convenience" — any clear professional urgency is acceptable; repeating "urgent/urgently" is not automatically penalised.
        7. A different clear, grammatically sound medication list (the exact house comma/semicolon form is not a universal template; ambiguity, grammar or safety impact is what scores).
        8. A descriptive number written as a digit — no fixed penalty unless standard usage, clarity or register is actually harmed.
        9. A pronoun-first paragraph with a clear referent; and natural use of "the patient" — flag only real ambiguity, repetition or impersonal-tone impact.
        10. An alternate clear DOB/patient-identification form — score genuine identification/professionalism problems, not template mismatch.
        11. Brackets/parentheses — not automatically wrong; assess readability/register impact.
        12. Familiar, profession-appropriate abbreviations the intended reader would understand.
        13. A clinically correct paraphrase/synonym, however far from Model Answer wording — Model Answer similarity contributes ZERO to the score.
        14. A different coherent paragraph order when task needs, clinical chronology and reader action remain clear.
        15. A clinically documented anxiety (or similar) diagnosis stated factually — a diagnosis is not a judgemental label.
        16. "type 2 diabetes mellitus" written with the digit — Model Answers use "type two" (OA-12); a candidate is never penalised for the digit.
        17. A clear professional opening other than "I am writing to ..." (OA-01/OA-02): Purpose is assessed semantically, never by template wording.
        18. The full patient name once in the introduction's purpose clause ("regarding Ms Isabel Garcia") — clear professional naming variations are accepted when clarity and cohesion are intact (OA-03/OA2-04).
        19. Different closure paragraphing or a closure request phrased differently from the Model Answer — house paragraphing is not imposed on candidates (OA-06/OA-07): duplication is judged semantically, never by phrase matching.
        20. Background placed somewhere other than a dedicated paragraph immediately before the closure (OA2-12) — assess logical organisation and relevance; the exact house paragraph position is never required of a candidate.
        21. A grammatically correct semicolon joining two related clauses (OA2-07) — narrative-semicolon avoidance is canonical Model Answer style; for a candidate judge clarity and sentence control, never the punctuation mark itself.
        22. Any professional semantic equivalent of the contact offer (OA2-19) — never score the contact sentence by exact phrase matching.
        23. A different but clear professional salutation where official task conventions permit it (OA2-17) — score a genuinely wrong or invented recipient, not a defensible alternative form.
        24. Common clinical diagnosis terms addressed to an allied-health reader (OA2-18): diabetes mellitus, hypothyroidism and arthritis/arthrosis are NOT "too medical" for an occupational therapist, physiotherapist, pharmacist or radiographer. Judge reader relevance — irrelevant specialist detail can still cost marks; correct professional terminology never does.
        25. A natural result construction that differs from the canonical "at" form (OA3-04) — "the white cell count was ...", "a white cell count of ...", "the temperature was ...", "a temperature of ..." are all correct FOR CANDIDATES; the "at" house wording is canonical only for Model Answers. Never penalise a candidate's grammatical, source-faithful result grammar.

        ALWAYS score as genuine errors: invented facts/dates/doses/diagnoses/admissions/discharges/patient identity; upgraded certainty (suspected -> confirmed, prophylaxis -> guarantee); an interpretation the notes never made (calling 88/70 mmHg "hypotension"); important omissions the recipient needs; wrong recipient/task action; delayed or vague purpose; tense changes that alter the timeline; grammar/punctuation/spelling errors; comma splices and incomplete constructions (e.g. "examination showed afebrile", "1000 white cells" where a count is meant, "on supine position"); mixed date families or abbreviated years; collapsed layout that harms professional readability; emotional/judgemental wording; colloquial register where a professional equivalent exists; unsafe unexplained shorthand; clinical values without units or with missing unit spaces; medication errors that affect clarity or safety.

        Clean answers stay clean: never manufacture a finding to fill a feedback template. Every finding must state the exact quote, the OET criterion it affects, why it matters for the reader, and a corrected wording.
        """;
}
