'use client';

import { useEffect, useState } from 'react';
import { Download } from 'lucide-react';
import { AdminTableLayout } from '@/components/admin/layout/admin-table-layout';
import { Button } from '@/components/admin/ui/button';
import { Badge } from '@/components/admin/ui/badge';
import { EmptyState } from '@/components/admin/ui/empty-state';
import { AsyncStateWrapper } from '@/components/state/async-state-wrapper';
import { DataTable, type Column } from '@/components/ui/data-table';
import { Toast } from '@/components/ui/alert';
import { getDocumentationExportsPageData, type DocumentationExportRow } from '@/lib/admin';
import { downloadDocumentationExportById } from '@/lib/api';
import { useAdminAuth } from '@/lib/hooks/use-admin-auth';

type PageStatus = 'loading' | 'success' | 'empty' | 'error';
type ToastState = { variant: 'success' | 'error'; message: string } | null;

function saveBlob(blob: Blob, fileName: string) {
  const objectUrl = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = objectUrl;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(objectUrl);
}

export default function DocumentationExportsPage() {
  const { isAuthenticated, role } = useAdminAuth();
  const [pageStatus, setPageStatus] = useState<PageStatus>('loading');
  const [retryNonce, setRetryNonce] = useState(0);
  const [rows, setRows] = useState<DocumentationExportRow[]>([]);
  const [downloadingId, setDownloadingId] = useState<string | null>(null);
  const [toast, setToast] = useState<ToastState>(null);

  useEffect(() => {
    let cancelled = false;
    async function load() {
      setPageStatus('loading');
      try {
        const items = await getDocumentationExportsPageData();
        if (cancelled) return;
        setRows(items);
        setPageStatus(items.length > 0 ? 'success' : 'empty');
      } catch (error) {
        console.error(error);
        if (!cancelled) {
          setPageStatus('error');
          setToast({ variant: 'error', message: 'Unable to load export history.' });
        }
      }
    }
    load();
    return () => {
      cancelled = true;
    };
  }, [retryNonce]);

  async function handleRedownload(row: DocumentationExportRow) {
    setDownloadingId(row.id);
    try {
      const result = await downloadDocumentationExportById(row.id);
      saveBlob(result.blob, result.fileName);
    } catch (error) {
      console.error(error);
      setToast({ variant: 'error', message: 'Unable to re-download this export.' });
    } finally {
      setDownloadingId(null);
    }
  }

  if (!isAuthenticated || role !== 'admin') return null;

  const breadcrumbs = [
    { label: 'Admin', href: '/admin' },
    { label: 'Documentation Center', href: '/admin/documentation-center' },
    { label: 'Export History' },
  ];

  const columns: Column<DocumentationExportRow>[] = [
    { key: 'exportType', header: 'Type', render: (e) => <span className="font-medium text-admin-fg-strong">{e.exportType}</span> },
    { key: 'mode', header: 'Mode', render: (e) => <Badge variant={e.mode === 'External' ? 'warning' : 'secondary'} size="sm">{e.mode}</Badge> },
    { key: 'moduleId', header: 'Module', render: (e) => <span className="text-admin-fg-muted">{e.moduleId ?? 'All'}</span> },
    { key: 'generatedAt', header: 'Generated', render: (e) => <span className="text-admin-fg-muted">{new Date(e.generatedAt).toLocaleString()}</span> },
    { key: 'generatedByName', header: 'Generated by', render: (e) => <span className="text-admin-fg-strong">{e.generatedByName}</span> },
    { key: 'sha256Hash', header: 'SHA-256', render: (e) => <span className="font-mono text-xs text-admin-fg-muted">{e.sha256Hash.slice(0, 16)}…</span> },
    {
      key: 'actions',
      header: '',
      render: (e) => (
        <Button
          variant="outline"
          size="sm"
          loading={downloadingId === e.id}
          onClick={() => handleRedownload(e)}
          startIcon={<Download className="h-3.5 w-3.5" />}
        >
          Re-download
        </Button>
      ),
    },
  ];

  return (
    <AdminTableLayout
      title="Export History"
      description="Every Master, module and Evidence Annex PDF ever generated, with its SHA-256 hash — prior versions remain retrievable, never silently overwritten."
      breadcrumbs={breadcrumbs}
    >
      {toast ? <Toast variant={toast.variant} message={toast.message} onClose={() => setToast(null)} /> : null}

      <AsyncStateWrapper
        status={pageStatus}
        onRetry={() => setRetryNonce((n) => n + 1)}
        emptyContent={<EmptyState title="No exports yet" description="Generate a PDF from the Documentation Center dashboard to see it here." />}
      >
        <DataTable aria-label="Export history" columns={columns} data={rows} keyExtractor={(e) => e.id} />
      </AsyncStateWrapper>
    </AdminTableLayout>
  );
}
