export const INCLUDED_LEARNER_DASHBOARD_PAGE_PATHS = [
  'app/page.tsx',
  'app/billing/page.tsx',
  'app/diagnostic/page.tsx',
  'app/diagnostic/hub/page.tsx',
  'app/diagnostic/results/page.tsx',
  'app/goals/page.tsx',
  'app/onboarding/page.tsx',
  'app/progress/page.tsx',
  'app/readiness/page.tsx',
  'app/study-plan/page.tsx',
  'app/settings/page.tsx',
  'app/settings/[section]/page.tsx',
  'app/submissions/page.tsx',
  'app/submissions/[id]/page.tsx',
  'app/submissions/compare/page.tsx',
  'app/listening/page.tsx',
  'app/listening/drills/[id]/page.tsx',
  'app/listening/results/[id]/page.tsx',
  'app/listening/review/[id]/page.tsx',
  'app/mocks/page.tsx',
  'app/mocks/player/[id]/page.tsx',
  'app/mocks/report/[id]/page.tsx',
  'app/mocks/setup/page.tsx',
  'app/reading/page.tsx',
  'app/reading/paper/[paperId]/page.tsx',
  'app/reading/paper/[paperId]/results/page.tsx',
  'app/speaking/page.tsx',
  'app/speaking/check/page.tsx',
  'app/speaking/expert-review/[id]/page.tsx',
  'app/speaking/phrasing/[id]/page.tsx',
  'app/speaking/results/[id]/page.tsx',
  'app/speaking/roleplay/[id]/page.tsx',
  'app/speaking/selection/page.tsx',
  'app/speaking/transcript/[id]/page.tsx',
  'app/writing/page.tsx',
  'app/writing/expert-request/page.tsx',
  'app/writing/library/page.tsx',
  'app/writing/model/page.tsx',
  'app/writing/result/page.tsx',
  'app/writing/revision/page.tsx',
  'app/recalls/page.tsx',
  'app/recalls/words/page.tsx',
  'app/recalls/cards/page.tsx',
  'app/recalls/library/page.tsx',
] as const;

export const EXCLUDED_IMMERSIVE_LEARNER_PAGE_PATHS = [
  'app/diagnostic/listening/page.tsx',
  'app/diagnostic/reading/page.tsx',
  'app/diagnostic/speaking/page.tsx',
  'app/diagnostic/writing/page.tsx',
  'app/reading/player/[id]/page.tsx',
  'app/listening/player/[id]/page.tsx',
  'app/writing/player/page.tsx',
  'app/writing/feedback/page.tsx',
  'app/speaking/task/[id]/page.tsx',
] as const;

export const LEARNER_DASHBOARD_REEXPORT_PAGE_PATHS = [
  'app/dashboard/project/page.tsx',
] as const;
