-- ═══════════════════════════════════════════════════════════════════════════
-- close-listening-incident-attempts.sql
--
-- Incident: INC-2026-CLAUDE-01 (Listening Part A advisory scorer retry storm).
-- Purpose:  Close the four known stuck Part A attempts by TAGGING them as
--           `skipped_no_evidence` so the repaired worker stops re-selecting
--           them. Manual, deliberate, one-shot-but-idempotent.
--
-- Hard safety contract
--   * TAG ONLY. No row is ever deleted. No table is dropped or truncated.
--   * Deterministic marking is untouched: "IsCorrect", "PointsEarned",
--     "MissReason", "SelectedDistractorCategory" are never in a SET clause,
--     and a before/after assertion aborts the transaction if any of them moved.
--   * "AiScoredAt" is never set — a skip is not an AI score.
--   * FAIL CLOSED: the read-only qualifying selection must identify EXACTLY
--     :expected_attempts attempts. Any other count aborts the whole
--     transaction with no writes.
--   * IDEMPOTENT: a row already stamped `skipped_no_evidence` still qualifies,
--     whether it was tagged by this script (incident id set) or closed by the
--     repaired scorer itself (incident id still NULL). A second run therefore
--     finds the same four attempts and updates zero rows.
--   * No attempt/user id is hard-coded — the set is derived by predicate, frozen
--     in time by :incident_cutoff.
--
-- Run (from /opt/oetwebapp on the VPS, production DB). The script lives on the
-- HOST, so it is piped into the container on stdin with `-f -`:
--   cd /opt/oetwebapp
--   docker exec -i -e PGPASSWORD="$POSTGRES_PASSWORD" oet-postgres \
--     psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -v ON_ERROR_STOP=1 \
--     -f - < scripts/ops/close-listening-incident-attempts.sql
--
-- Overrides go BEFORE `-f -` (psql reads the script last), e.g.:
--   docker exec -i -e PGPASSWORD="$POSTGRES_PASSWORD" oet-postgres \
--     psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -v ON_ERROR_STOP=1 \
--     -v expected_attempts=4 -v incident_cutoff=2026-08-26T11:00:00Z \
--     -f - < scripts/ops/close-listening-incident-attempts.sql
--
-- Preview first with scripts/ops/export-ai-incident-evidence.sql section 4.
-- If the count is not 4, DO NOT edit this file blindly: re-run the export and
-- confirm with the incident commander before overriding -v expected_attempts.
-- ═══════════════════════════════════════════════════════════════════════════

\set ON_ERROR_STOP on
\pset border 2
\pset format aligned

\if :{?expected_attempts}
\else
\set expected_attempts 4
\endif

-- Stable inclusive incident cutoff — the reason "exactly four" stays exactly
-- four. Production evidence (read-only) put the last qualifying submission at
-- 2026-08-26T10:49:58.902864Z, so an inclusive bound of 2026-08-26T11:00:00Z
-- covers all four attempts and can never grow. Without it the qualifying
-- predicate is open-ended: any evidence-free attempt submitted AFTER the
-- incident would join the set, make found <> expected, and abort this script
-- for the wrong reason — or, if someone raised expected_attempts to match, be
-- tagged with an incident id it has nothing to do with. The bound therefore
-- protects both the fail-closed assertion and the accuracy of the tag.
\if :{?incident_cutoff}
\else
\set incident_cutoff '2026-08-26T11:00:00Z'
\endif

\set incident_id 'INC-2026-CLAUDE-01'
\set skip_reason 'skipped_no_evidence'

-- Enum ordinals (EF stores these as int):
--   ListeningAttemptStatus.Submitted     = 1
--   ListeningQuestionType.ShortAnswer    = 0
--   ListeningQuestionType.FillInBlank    = 2
--   AssessmentGovernanceStatus.Effective = 3

BEGIN;

CREATE TEMP TABLE incident_params ON COMMIT DROP AS
SELECT
    :'incident_id'::text            AS incident_id,
    :'skip_reason'::text            AS skip_reason,
    :expected_attempts::int         AS expected_attempts,
    :'incident_cutoff'::timestamptz AS incident_cutoff;

-- ── 1. Read-only qualifying selection ──────────────────────────────────────
-- A qualifying attempt is a SUBMITTED attempt, submitted at or before the
-- incident cutoff, whose Part A answers are all un-AI-scored, are still open OR
-- already closed as `skipped_no_evidence` (tagged by this incident or untagged
-- because the repaired scorer stamped them itself), and for which NOT ONE gap
-- has an effective author-approved rationale (i.e. the scorer had zero eligible
-- evidence and could never have produced a verdict).
--
-- The cutoff is what keeps the fail-closed count stable: it freezes the
-- population to the four attempts the read-only export already evidenced, so
-- work submitted after the incident can never silently enter the tagged set. A
-- NULL "SubmittedAt" fails the comparison and is excluded on purpose — that
-- lowers the count and aborts rather than tagging an attempt whose submission
-- time is unknown.
--
-- Any OTHER terminal skip reason (credential_quarantined, provider_rejected,
-- indeterminate_timeout, no_matching_verdicts, retries_exhausted) is a
-- different failure mode and is deliberately NOT in scope here.
-- `credential_quarantined` work is recovered separately and explicitly by
-- scripts/ops/requeue-listening-credential-quarantined.sql, AFTER the
-- replacement credential is activated and canaried. Identical predicate in
-- export-ai-incident-evidence.sql section 4 — keep them aligned.
CREATE TEMP TABLE incident_answers ON COMMIT DROP AS
WITH parta AS (
    SELECT
        a."Id"                  AS answer_id,
        a."ListeningAttemptId"  AS attempt_id,
        (r."Id" IS NOT NULL)    AS has_effective_rationale
    FROM "ListeningAnswers" a
    JOIN "ListeningQuestions" q  ON q."Id"  = a."ListeningQuestionId"
    JOIN "ListeningAttempts"  at ON at."Id" = a."ListeningAttemptId"
    LEFT JOIN "AssessmentRationales" r
           ON r."Assessment"         = 'listening'
          AND r."QuestionRevisionId" = q."Id"
          AND r."Status"             = 3
    WHERE at."Status" = 1
      AND at."SubmittedAt" <= (SELECT incident_cutoff FROM incident_params)
      AND q."QuestionType" IN (0, 2)
      AND a."AiScoredAt" IS NULL
      AND (
            a."AiSkipReason" IS NULL
            OR (a."AiSkipReason" = (SELECT skip_reason FROM incident_params)
                AND (a."AiIncidentId" IS NULL
                     OR a."AiIncidentId" = (SELECT incident_id FROM incident_params)))
          )
),
qualifying_attempts AS (
    SELECT attempt_id
    FROM parta
    GROUP BY attempt_id
    HAVING count(*) FILTER (WHERE has_effective_rationale) = 0
)
SELECT p.answer_id, p.attempt_id
FROM parta p
JOIN qualifying_attempts qa ON qa.attempt_id = p.attempt_id;

\echo '-- Qualifying attempts identified by the read-only selection:'
SELECT attempt_id, count(*) AS parta_answers
FROM incident_answers
GROUP BY attempt_id
ORDER BY attempt_id;

-- ── 2. Fail closed on any unexpected scope ─────────────────────────────────
DO $$
DECLARE
    found_attempts int;
    expected int;
BEGIN
    SELECT expected_attempts INTO expected FROM incident_params;
    SELECT count(DISTINCT attempt_id) INTO found_attempts FROM incident_answers;

    IF found_attempts <> expected THEN
        RAISE EXCEPTION
            'INC closure aborted: expected exactly % qualifying stuck attempt(s), found %. No rows changed.',
            expected, found_attempts;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM incident_answers) THEN
        RAISE EXCEPTION 'INC closure aborted: qualifying selection is empty. No rows changed.';
    END IF;
END $$;

-- ── 3. Snapshot the deterministic mark before touching anything ────────────
CREATE TEMP TABLE incident_score_before ON COMMIT DROP AS
SELECT
    a."Id"                          AS answer_id,
    a."IsCorrect"                   AS is_correct,
    a."PointsEarned"                AS points_earned,
    a."MissReason"                  AS miss_reason,
    a."SelectedDistractorCategory"  AS distractor_category,
    a."AiScoredAt"                  AS ai_scored_at,
    a."AiVerdict"                   AS ai_verdict
FROM "ListeningAnswers" a
JOIN incident_answers ia ON ia.answer_id = a."Id";

-- ── 4. Tag (never delete, never re-score) ──────────────────────────────────
UPDATE "ListeningAnswers" a
SET "AiSkipReason"   = (SELECT skip_reason FROM incident_params),
    "AiIncidentId"   = (SELECT incident_id FROM incident_params),
    "AiNextAttemptAt" = NULL
FROM incident_answers ia
WHERE a."Id" = ia.answer_id
  AND (
        a."AiSkipReason"  IS DISTINCT FROM (SELECT skip_reason FROM incident_params)
     OR a."AiIncidentId"  IS DISTINCT FROM (SELECT incident_id FROM incident_params)
     OR a."AiNextAttemptAt" IS NOT NULL
      );

-- ── 5. Prove the deterministic mark did not move ───────────────────────────
DO $$
DECLARE
    drifted int;
BEGIN
    SELECT count(*) INTO drifted
    FROM incident_score_before b
    JOIN "ListeningAnswers" a ON a."Id" = b.answer_id
    WHERE a."IsCorrect"                  IS DISTINCT FROM b.is_correct
       OR a."PointsEarned"               IS DISTINCT FROM b.points_earned
       OR a."MissReason"                 IS DISTINCT FROM b.miss_reason
       OR a."SelectedDistractorCategory" IS DISTINCT FROM b.distractor_category
       OR a."AiScoredAt"                 IS DISTINCT FROM b.ai_scored_at
       OR a."AiVerdict"                  IS DISTINCT FROM b.ai_verdict;

    IF drifted > 0 THEN
        RAISE EXCEPTION
            'INC closure aborted: % answer row(s) had a deterministic/advisory field changed. Rolling back.',
            drifted;
    END IF;
END $$;

-- ── 6. Verification output ─────────────────────────────────────────────────
\echo '-- Post-closure state (deterministic mark must be identical to pre-state):'
SELECT
    a."ListeningAttemptId"      AS attempt_id,
    count(*)                    AS tagged_answers,
    min(a."AiSkipReason")       AS skip_reason,
    min(a."AiIncidentId")       AS incident_id,
    count(*) FILTER (WHERE a."AiScoredAt" IS NOT NULL)  AS falsely_ai_scored,
    sum(a."PointsEarned")       AS deterministic_points,
    count(*) FILTER (WHERE a."IsCorrect") AS deterministic_correct
FROM "ListeningAnswers" a
JOIN incident_answers ia ON ia.answer_id = a."Id"
GROUP BY a."ListeningAttemptId"
ORDER BY a."ListeningAttemptId";

COMMIT;

\echo '-- INC-2026-CLAUDE-01 closure committed. Re-running this file is a no-op.'
