using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace OetWithDrHesham.Api.Domain;

// ═════════════════════════════════════════════════════════════════════════════
// Listening Module Pathway — Phase 2–5 Domain Entities
//
// Builds on the Phase 1 schema (ListeningPathwayEntities.cs). Adds:
//   Phase 2: ListeningLesson + LearnerListeningLessonProgress (8 sub-skill bootcamps)
//   Phase 3: ListeningDailyPlanItem (daily practice engine)
//            ListeningStrategy + LearnerListeningStrategyProgress (30+ strategies)
//   Phase 4: PronunciationCard + LearnerPronunciationCard (SM-2 healthcare vocab)
//            DictationDrill + LearnerDictationProgress
//   Phase 5: ListeningMockTemplate (full mock test composition)
//
// Naming convention: `Listening*` prefix where the domain warrants it;
// `Learner*` prefix for per-user progress rows. Avoids collisions with
// Reading equivalents (e.g. PronunciationCard is distinct from VocabularyWord).
// ═════════════════════════════════════════════════════════════════════════════

/// <summary>Phase 2 — Foundation lesson (one per L1..L8 sub-skill).</summary>
public class ListeningLesson
{
    public Guid Id { get; set; }
    [MaxLength(128)] public string Slug { get; set; } = default!;
    [MaxLength(256)] public string Title { get; set; } = default!;
    [MaxLength(256)] public string TitleAr { get; set; } = "";
    [MaxLength(4)] public string SkillCode { get; set; } = default!;   // L1..L8
    public int OrderIndex { get; set; }
    public int EstimatedMinutes { get; set; }
    public string? VideoUrl { get; set; }
    public string BodyMarkdownEn { get; set; } = "";
    public string BodyMarkdownAr { get; set; } = "";
    /// <summary>JSON-serialized list of <see cref="ListeningQuestion.Id"/> (string keys).</summary>
    public string DrillQuestionIdsJson { get; set; } = "[]";
    public string QuizQuestionIdsJson { get; set; } = "[]";
    public Guid? PrerequisiteLessonId { get; set; }
    public bool IsPublished { get; set; }
}

/// <summary>Phase 2 — per-learner foundation lesson progress.</summary>
public class LearnerListeningLessonProgress
{
    public Guid Id { get; set; }
    [MaxLength(64)] public string UserId { get; set; } = default!;
    public Guid LessonId { get; set; }
    public bool VideoWatched { get; set; }
    public bool BodyRead { get; set; }
    public bool Drill1Completed { get; set; }
    public bool Drill2Completed { get; set; }
    public bool Drill3Completed { get; set; }
    public int? QuizScore { get; set; }
    public int QuizAttempts { get; set; }
    public DateTimeOffset? CompletedAt { get; set; }
}

/// <summary>Phase 3 — single daily plan item generated by the daily plan engine.</summary>
public class ListeningDailyPlanItem
{
    public Guid Id { get; set; }
    [MaxLength(64)] public string UserId { get; set; } = default!;
    public DateOnly PlanDate { get; set; }
    public int Ordinal { get; set; }
    /// <summary>drill | accent_drill | dictation | pronunciation_review | wrong_review |
    /// lesson | mock | strategy_read</summary>
    [MaxLength(32)] public string ItemType { get; set; } = default!;
    [MaxLength(4)] public string? FocusSkill { get; set; }
    [MaxLength(16)] public string? FocusAccent { get; set; }
    public int EstimatedMinutes { get; set; }
    public string PayloadJson { get; set; } = "{}";
    [MaxLength(16)] public string Status { get; set; } = "pending";
    public DateTimeOffset? StartedAt { get; set; }
    public DateTimeOffset? CompletedAt { get; set; }
}

/// <summary>Phase 3 — strategy article (e.g. "The Skeleton Method").</summary>
public class ListeningStrategy
{
    public Guid Id { get; set; }
    [MaxLength(128)] public string Slug { get; set; } = default!;
    [MaxLength(256)] public string Title { get; set; } = default!;
    [MaxLength(256)] public string TitleAr { get; set; } = "";
    [MaxLength(64)] public string Category { get; set; } = default!;
    /// <summary>JSON: ["A","B","C"]</summary>
    public string ApplicablePartsJson { get; set; } = "[]";
    public int EstimatedReadMinutes { get; set; }
    public string BodyMarkdownEn { get; set; } = "";
    public string BodyMarkdownAr { get; set; } = "";
    public string? VideoUrl { get; set; }
    public string? AudioUrl { get; set; }
    public Guid? LinkedDrillId { get; set; }
    [MaxLength(32)] public string UnlockStage { get; set; } = "foundation";
    public int Difficulty { get; set; }
    public bool IsPublished { get; set; }
}

/// <summary>Phase 3 — per-learner strategy progress.</summary>
public class LearnerListeningStrategyProgress
{
    public Guid Id { get; set; }
    [MaxLength(64)] public string UserId { get; set; } = default!;
    public Guid StrategyId { get; set; }
    public bool MarkedAsRead { get; set; }
    public bool Favorited { get; set; }
    public DateTimeOffset ReadAt { get; set; }
}

/// <summary>Phase 4 — healthcare vocabulary pronunciation card (master).</summary>
public class PronunciationCard
{
    public Guid Id { get; set; }
    [MaxLength(128)] public string Word { get; set; } = default!;
    [MaxLength(128)] public string PronunciationIpa { get; set; } = "";
    [MaxLength(128)] public string BritishIpa { get; set; } = "";
    [MaxLength(128)] public string AustralianIpa { get; set; } = "";
    [MaxLength(128)] public string AmericanIpa { get; set; } = "";
    public string? AudioBritishUrl { get; set; }
    public string? AudioAustralianUrl { get; set; }
    public string? AudioAmericanUrl { get; set; }
    public string DefinitionEn { get; set; } = "";
    public string DefinitionAr { get; set; } = "";
    public int SyllableCount { get; set; }
    [MaxLength(64)] public string StressPattern { get; set; } = "";
    public string CommonMispronunciationsJson { get; set; } = "[]";
    public string SimilarSoundingTrapsJson { get; set; } = "[]";
    public int Difficulty { get; set; }
    public string ProfessionRelevanceJson { get; set; } = "[]";
    public DateTimeOffset CreatedAt { get; set; }
}

/// <summary>Phase 4 — per-learner SM-2 state for a pronunciation card.</summary>
public class LearnerPronunciationCard
{
    public Guid Id { get; set; }
    [MaxLength(64)] public string UserId { get; set; } = default!;
    public Guid PronunciationCardId { get; set; }
    [MaxLength(32)] public string Source { get; set; } = "manual";
    public decimal Easiness { get; set; } = 2.5m;
    public int IntervalDays { get; set; } = 1;
    public int Repetitions { get; set; }
    public int RetentionScore { get; set; }
    public DateTimeOffset NextReviewAt { get; set; }
    public DateTimeOffset? LastReviewedAt { get; set; }
    public DateTimeOffset AddedAt { get; set; }
}

/// <summary>Phase 4 — dictation drill master record.</summary>
public class DictationDrill
{
    public Guid Id { get; set; }
    /// <summary>single_term | short_phrase | full_sentence | mini_consultation</summary>
    [MaxLength(32)] public string DrillType { get; set; } = default!;
    [MaxLength(256)] public string? AudioAssetUrl { get; set; }
    public int DurationSeconds { get; set; }
    public string TranscriptText { get; set; } = "";
    public string AcceptableVariantsJson { get; set; } = "[]";
    [MaxLength(16)] public string Accent { get; set; } = "en-GB";
    public int Difficulty { get; set; }
    public string ProfessionRelevanceJson { get; set; } = "[]";
    public bool IsPublished { get; set; }
    public DateTimeOffset CreatedAt { get; set; }
}

/// <summary>Phase 4 — per-learner dictation attempt + SR state.</summary>
public class LearnerDictationProgress
{
    public Guid Id { get; set; }
    [MaxLength(64)] public string UserId { get; set; } = default!;
    public Guid DictationDrillId { get; set; }
    public string? LearnerAnswer { get; set; }
    public bool IsCorrect { get; set; }
    public int Attempts { get; set; }
    public DateTimeOffset? NextReviewAt { get; set; }
    public DateTimeOffset LastAttemptedAt { get; set; }
}

/// <summary>Phase 5 — mock test template (composed of audio+question references).</summary>
public class ListeningMockTemplate
{
    public Guid Id { get; set; }
    [MaxLength(256)] public string Title { get; set; } = default!;
    public int Difficulty { get; set; }
    /// <summary>JSON: ordered string[] of ListeningQuestion.Id (42 entries).</summary>
    public string QuestionIdsJson { get; set; } = "[]";
    public int DurationSeconds { get; set; } = 45 * 60;
    public bool IsPublished { get; set; }
    public DateTimeOffset CreatedAt { get; set; }
}
