using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace OetLearner.Api.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddRuntimeSettings : Migration
    {
        // NOTE: Generated by `dotnet ef migrations add AddRuntimeSettings`. The
        // raw scaffold also picked up unrelated pre-existing snapshot drift
        // (two ConversationSettings columns + LaunchReadinessSettings table)
        // whose Designer.cs files were never committed. Those changes are
        // already live in production via earlier migrations, so this file is
        // trimmed to ONLY contain the genuinely new RuntimeSettings table.
        // The snapshot continues to track all model state.

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "RuntimeSettings",
                columns: table => new
                {
                    Id = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    BrevoApiKeyEncrypted = table.Column<string>(type: "text", nullable: true),
                    BrevoEmailVerificationTemplateId = table.Column<int>(type: "integer", nullable: true),
                    BrevoPasswordResetTemplateId = table.Column<int>(type: "integer", nullable: true),
                    SmtpHost = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    SmtpPort = table.Column<int>(type: "integer", nullable: true),
                    SmtpUsername = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    SmtpPasswordEncrypted = table.Column<string>(type: "text", nullable: true),
                    SmtpFromAddress = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    SmtpFromName = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    StripeSecretKeyEncrypted = table.Column<string>(type: "text", nullable: true),
                    StripePublishableKey = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    StripeWebhookSecretEncrypted = table.Column<string>(type: "text", nullable: true),
                    StripeSuccessUrl = table.Column<string>(type: "character varying(1024)", maxLength: 1024, nullable: true),
                    StripeCancelUrl = table.Column<string>(type: "character varying(1024)", maxLength: 1024, nullable: true),
                    SentryDsn = table.Column<string>(type: "character varying(512)", maxLength: 512, nullable: true),
                    SentryEnvironment = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true),
                    SentrySampleRate = table.Column<double>(type: "double precision", nullable: true),
                    BackupS3Url = table.Column<string>(type: "character varying(1024)", maxLength: 1024, nullable: true),
                    BackupAwsAccessKeyId = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    BackupAwsSecretAccessKeyEncrypted = table.Column<string>(type: "text", nullable: true),
                    BackupGpgPassphraseEncrypted = table.Column<string>(type: "text", nullable: true),
                    BackupAlertWebhook = table.Column<string>(type: "character varying(1024)", maxLength: 1024, nullable: true),
                    GoogleClientId = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    GoogleClientSecretEncrypted = table.Column<string>(type: "text", nullable: true),
                    AppleClientId = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    AppleTeamId = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true),
                    AppleKeyId = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true),
                    ApplePrivateKeyEncrypted = table.Column<string>(type: "text", nullable: true),
                    FacebookAppId = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    FacebookAppSecretEncrypted = table.Column<string>(type: "text", nullable: true),
                    ApnsKeyId = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true),
                    ApnsTeamId = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true),
                    ApnsBundleId = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    ApnsAuthKeyEncrypted = table.Column<string>(type: "text", nullable: true),
                    FcmServerKeyEncrypted = table.Column<string>(type: "text", nullable: true),
                    FcmProjectId = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    UpdatedByUserId = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true),
                    UpdatedByUserName = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: true),
                    UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RuntimeSettings", x => x.Id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "RuntimeSettings");
        }
    }
}
