#!/usr/bin/env bash
# Static deployment contract for the production compute-offload path.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
WORKFLOW="$REPO_ROOT/.github/workflows/deploy.yml"
ROLLOUT="$SCRIPT_DIR/auto-deploy-ghcr.sh"
IMMUTABLE_ROLLOUT="$SCRIPT_DIR/rollout-release.sh"
PREFLIGHT="$SCRIPT_DIR/pre-flight.sh"

require_literal() {
  local file="$1"
  local literal="$2"
  if ! grep -Fq -- "$literal" "$file"; then
    echo "[compute-offload] missing required contract in $file: $literal" >&2
    exit 1
  fi
}

require_literal "$WORKFLOW" 'dotnet ef migrations script --idempotent'
require_literal "$WORKFLOW" 'apply-migrations-from-ci.sh'
require_literal "$WORKFLOW" 'migrate-production'
require_literal "$ROLLOUT" '--no-build'
require_literal "$ROLLOUT" 'DB_BACKUP_IMAGE'
require_literal "$IMMUTABLE_ROLLOUT" '--no-build'
require_literal "$PREFLIGHT" '--no-build'

active_commands="$(sed '/^[[:space:]]*#/d' "$ROLLOUT")"
if printf '%s\n' "$active_commands" | grep -Eiq \
  'docker[[:space:]]+(compose|[-a-z]+)[^\n]*([[:space:]])build([[:space:]]|$)|(^|[[:space:]])(pnpm|npm)[[:space:]]+[^\n]*(build|test|lint)([[:space:]]|$)|(^|[[:space:]])dotnet[[:space:]]+(build|test|publish)([[:space:]]|$)'; then
  echo "[compute-offload] active VPS rollout contains a source build/test command" >&2
  exit 1
fi

echo "[compute-offload] CI owns eligible build/test/migration-generation work; VPS rollout is pull-only"
#!/usr/bin/env bash
# Static CI guard for the production compute boundary.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
WORKFLOW="$REPO_ROOT/.github/workflows/deploy.yml"
ROLLOUT="$SCRIPT_DIR/auto-deploy-ghcr.sh"

require_match() {
  local pattern="$1"
  local file="$2"
  local message="$3"
  if ! grep -Eq -- "$pattern" "$file"; then
    echo "[compute-guard] $message" >&2
    exit 1
  fi
}

require_match '^  migrate-production:' "$WORKFLOW" \
  "deploy workflow must generate/apply migrations in the migrate-production Actions job."
require_match 'dotnet ef migrations script --idempotent' "$WORKFLOW" \
  "migration SQL must be generated by dotnet-ef on GitHub Actions."
require_match 'apply-migrations-from-ci\.sh' "$WORKFLOW" \
  "production migration application must use the reviewed stdin wrapper."
require_match 'needs: \[build-web, build-api, build-backup, migrate-production\]' "$WORKFLOW" \
  "deploy must wait for the Actions migration gate."
require_match '--no-build' "$ROLLOUT" \
  "the active VPS rollout must start containers with --no-build."
require_match 'ALLOW_VPS_SOURCE_BUILD=owner-approved-emergency' "$REPO_ROOT/scripts/deploy-production.sh" \
  "the legacy source-build fallback must be explicitly gated."
require_match 'ALLOW_VPS_SOURCE_BUILD=owner-approved-emergency' "$REPO_ROOT/scripts/deploy/deploy-direct.sh" \
  "the legacy direct source-build fallback must be explicitly gated."

active_commands="$(sed '/^[[:space:]]*#/d' "$ROLLOUT")"
if printf '%s\n' "$active_commands" | grep -Eiq \
  'docker[[:space:]]+(compose|[-a-z]+)[^\n]*([[:space:]])build([[:space:]]|$)|\b(pnpm|npm)[[:space:]]+[^\n]*\b(build|test)\b|\bdotnet[[:space:]]+(build|test|publish)\b'; then
  echo "[compute-guard] active VPS rollout contains a source build/test/publish command." >&2
  exit 1
fi

echo "[compute-guard] Actions owns build, test, image-packaging, and migration generation; VPS owns only image/data/runtime gates."
