#!/usr/bin/env bash
set -euo pipefail
echo "=== ALIVE GENERATORS ==="
pgrep -af 'node scripts/admin/' | grep -v defunct || echo "(none)"
echo ""
echo "=== LISTENING ==="
tail -8 /tmp/generate-listening-live.log 2>/dev/null || echo "(no log)"
echo "  TTS errors: $(grep -cE 'TTS 400' /tmp/generate-listening-live.log 2>/dev/null || echo 0)"
echo "  Published:  $(grep -c 'listening-publish.*Published\|✓ published' /tmp/generate-listening-live.log 2>/dev/null || echo 0)"
echo ""
echo "=== READING ==="
tail -6 /tmp/generate-reading-live.log 2>/dev/null || echo "(no log)"
echo ""
echo "=== GRAMMAR ==="
tail -3 /tmp/generate-grammar-live.log 2>/dev/null || echo "(no log)"
echo ""
echo "=== PRONUNCIATION ==="
tail -3 /tmp/generate-pronunciation-live.log 2>/dev/null || echo "(no log)"
echo ""
echo "=== VOCAB ==="
tail -3 /tmp/vocab-live.log 2>/dev/null || echo "(no log)"
echo ""
echo "=== BACKEND ERRORS (last 5m, non-access) ==="
docker logs --since 5m oet-api 2>&1 | grep -vE 'HTTP/1.1" [0-9]{3}' | grep -iE 'exception|error|warn|fail|stacktrace|aigateway' | tail -30 || echo "(none)"
