/**
 * Comprehensive ISO 3166-1 alpha-2 country list with E.164 dial codes.
 * Used by the phone-number country selector across web, desktop, and mobile.
 */

export interface CountryEntry {
  /** Lower-case ISO 3166-1 alpha-2 code, used as the stored value. */
  value: string;
  /** Display label (English country name). */
  label: string;
  /** E.164 dial code including the leading '+'. */
  dialCode: string;
  /** Upper-case ISO 3166-1 alpha-2 code (for flag rendering). */
  isoCode: string;
}

/**
 * Common destinations surfaced first in the selector. These match the
 * original 10-country list shipped with the registration form so saved
 * defaults remain stable.
 */
export const PRIORITY_COUNTRY_ISO: ReadonlyArray<string> = [
  'PK', 'IN', 'BD', 'AE', 'SA', 'QA', 'GB', 'AU', 'US', 'CA',
];

/**
 * Full country list (alphabetical). Includes UN member states and widely
 * used dependent territories with assigned country-calling codes.
 */
const ALL_COUNTRIES: ReadonlyArray<Omit<CountryEntry, 'value'>> = [
  { label: 'Afghanistan', dialCode: '+93', isoCode: 'AF' },
  { label: 'Åland Islands', dialCode: '+358', isoCode: 'AX' },
  { label: 'Albania', dialCode: '+355', isoCode: 'AL' },
  { label: 'Algeria', dialCode: '+213', isoCode: 'DZ' },
  { label: 'American Samoa', dialCode: '+1684', isoCode: 'AS' },
  { label: 'Andorra', dialCode: '+376', isoCode: 'AD' },
  { label: 'Angola', dialCode: '+244', isoCode: 'AO' },
  { label: 'Anguilla', dialCode: '+1264', isoCode: 'AI' },
  { label: 'Antigua and Barbuda', dialCode: '+1268', isoCode: 'AG' },
  { label: 'Argentina', dialCode: '+54', isoCode: 'AR' },
  { label: 'Armenia', dialCode: '+374', isoCode: 'AM' },
  { label: 'Aruba', dialCode: '+297', isoCode: 'AW' },
  { label: 'Australia', dialCode: '+61', isoCode: 'AU' },
  { label: 'Austria', dialCode: '+43', isoCode: 'AT' },
  { label: 'Azerbaijan', dialCode: '+994', isoCode: 'AZ' },
  { label: 'Bahamas', dialCode: '+1242', isoCode: 'BS' },
  { label: 'Bahrain', dialCode: '+973', isoCode: 'BH' },
  { label: 'Bangladesh', dialCode: '+880', isoCode: 'BD' },
  { label: 'Barbados', dialCode: '+1246', isoCode: 'BB' },
  { label: 'Belarus', dialCode: '+375', isoCode: 'BY' },
  { label: 'Belgium', dialCode: '+32', isoCode: 'BE' },
  { label: 'Belize', dialCode: '+501', isoCode: 'BZ' },
  { label: 'Benin', dialCode: '+229', isoCode: 'BJ' },
  { label: 'Bermuda', dialCode: '+1441', isoCode: 'BM' },
  { label: 'Bhutan', dialCode: '+975', isoCode: 'BT' },
  { label: 'Bolivia', dialCode: '+591', isoCode: 'BO' },
  { label: 'Bosnia and Herzegovina', dialCode: '+387', isoCode: 'BA' },
  { label: 'Botswana', dialCode: '+267', isoCode: 'BW' },
  { label: 'Brazil', dialCode: '+55', isoCode: 'BR' },
  { label: 'British Indian Ocean Territory', dialCode: '+246', isoCode: 'IO' },
  { label: 'British Virgin Islands', dialCode: '+1284', isoCode: 'VG' },
  { label: 'Brunei', dialCode: '+673', isoCode: 'BN' },
  { label: 'Bulgaria', dialCode: '+359', isoCode: 'BG' },
  { label: 'Burkina Faso', dialCode: '+226', isoCode: 'BF' },
  { label: 'Burundi', dialCode: '+257', isoCode: 'BI' },
  { label: 'Cambodia', dialCode: '+855', isoCode: 'KH' },
  { label: 'Cameroon', dialCode: '+237', isoCode: 'CM' },
  { label: 'Canada', dialCode: '+1', isoCode: 'CA' },
  { label: 'Cape Verde', dialCode: '+238', isoCode: 'CV' },
  { label: 'Cayman Islands', dialCode: '+1345', isoCode: 'KY' },
  { label: 'Central African Republic', dialCode: '+236', isoCode: 'CF' },
  { label: 'Chad', dialCode: '+235', isoCode: 'TD' },
  { label: 'Chile', dialCode: '+56', isoCode: 'CL' },
  { label: 'China', dialCode: '+86', isoCode: 'CN' },
  { label: 'Christmas Island', dialCode: '+61', isoCode: 'CX' },
  { label: 'Cocos (Keeling) Islands', dialCode: '+61', isoCode: 'CC' },
  { label: 'Colombia', dialCode: '+57', isoCode: 'CO' },
  { label: 'Comoros', dialCode: '+269', isoCode: 'KM' },
  { label: 'Congo (Republic)', dialCode: '+242', isoCode: 'CG' },
  { label: 'Congo (DR)', dialCode: '+243', isoCode: 'CD' },
  { label: 'Cook Islands', dialCode: '+682', isoCode: 'CK' },
  { label: 'Costa Rica', dialCode: '+506', isoCode: 'CR' },
  { label: 'Croatia', dialCode: '+385', isoCode: 'HR' },
  { label: 'Cuba', dialCode: '+53', isoCode: 'CU' },
  { label: 'Curaçao', dialCode: '+599', isoCode: 'CW' },
  { label: 'Cyprus', dialCode: '+357', isoCode: 'CY' },
  { label: 'Czechia', dialCode: '+420', isoCode: 'CZ' },
  { label: 'Denmark', dialCode: '+45', isoCode: 'DK' },
  { label: 'Djibouti', dialCode: '+253', isoCode: 'DJ' },
  { label: 'Dominica', dialCode: '+1767', isoCode: 'DM' },
  { label: 'Dominican Republic', dialCode: '+1809', isoCode: 'DO' },
  { label: 'Ecuador', dialCode: '+593', isoCode: 'EC' },
  { label: 'Egypt', dialCode: '+20', isoCode: 'EG' },
  { label: 'El Salvador', dialCode: '+503', isoCode: 'SV' },
  { label: 'Equatorial Guinea', dialCode: '+240', isoCode: 'GQ' },
  { label: 'Eritrea', dialCode: '+291', isoCode: 'ER' },
  { label: 'Estonia', dialCode: '+372', isoCode: 'EE' },
  { label: 'Eswatini', dialCode: '+268', isoCode: 'SZ' },
  { label: 'Ethiopia', dialCode: '+251', isoCode: 'ET' },
  { label: 'Falkland Islands', dialCode: '+500', isoCode: 'FK' },
  { label: 'Faroe Islands', dialCode: '+298', isoCode: 'FO' },
  { label: 'Fiji', dialCode: '+679', isoCode: 'FJ' },
  { label: 'Finland', dialCode: '+358', isoCode: 'FI' },
  { label: 'France', dialCode: '+33', isoCode: 'FR' },
  { label: 'French Guiana', dialCode: '+594', isoCode: 'GF' },
  { label: 'French Polynesia', dialCode: '+689', isoCode: 'PF' },
  { label: 'Gabon', dialCode: '+241', isoCode: 'GA' },
  { label: 'Gambia', dialCode: '+220', isoCode: 'GM' },
  { label: 'Georgia', dialCode: '+995', isoCode: 'GE' },
  { label: 'Germany', dialCode: '+49', isoCode: 'DE' },
  { label: 'Ghana', dialCode: '+233', isoCode: 'GH' },
  { label: 'Gibraltar', dialCode: '+350', isoCode: 'GI' },
  { label: 'Greece', dialCode: '+30', isoCode: 'GR' },
  { label: 'Greenland', dialCode: '+299', isoCode: 'GL' },
  { label: 'Grenada', dialCode: '+1473', isoCode: 'GD' },
  { label: 'Guadeloupe', dialCode: '+590', isoCode: 'GP' },
  { label: 'Guam', dialCode: '+1671', isoCode: 'GU' },
  { label: 'Guatemala', dialCode: '+502', isoCode: 'GT' },
  { label: 'Guernsey', dialCode: '+44', isoCode: 'GG' },
  { label: 'Guinea', dialCode: '+224', isoCode: 'GN' },
  { label: 'Guinea-Bissau', dialCode: '+245', isoCode: 'GW' },
  { label: 'Guyana', dialCode: '+592', isoCode: 'GY' },
  { label: 'Haiti', dialCode: '+509', isoCode: 'HT' },
  { label: 'Honduras', dialCode: '+504', isoCode: 'HN' },
  { label: 'Hong Kong', dialCode: '+852', isoCode: 'HK' },
  { label: 'Hungary', dialCode: '+36', isoCode: 'HU' },
  { label: 'Iceland', dialCode: '+354', isoCode: 'IS' },
  { label: 'India', dialCode: '+91', isoCode: 'IN' },
  { label: 'Indonesia', dialCode: '+62', isoCode: 'ID' },
  { label: 'Iran', dialCode: '+98', isoCode: 'IR' },
  { label: 'Iraq', dialCode: '+964', isoCode: 'IQ' },
  { label: 'Ireland', dialCode: '+353', isoCode: 'IE' },
  { label: 'Isle of Man', dialCode: '+44', isoCode: 'IM' },
  { label: 'Israel', dialCode: '+972', isoCode: 'IL' },
  { label: 'Italy', dialCode: '+39', isoCode: 'IT' },
  { label: 'Ivory Coast', dialCode: '+225', isoCode: 'CI' },
  { label: 'Jamaica', dialCode: '+1876', isoCode: 'JM' },
  { label: 'Japan', dialCode: '+81', isoCode: 'JP' },
  { label: 'Jersey', dialCode: '+44', isoCode: 'JE' },
  { label: 'Jordan', dialCode: '+962', isoCode: 'JO' },
  { label: 'Kazakhstan', dialCode: '+7', isoCode: 'KZ' },
  { label: 'Kenya', dialCode: '+254', isoCode: 'KE' },
  { label: 'Kiribati', dialCode: '+686', isoCode: 'KI' },
  { label: 'Kosovo', dialCode: '+383', isoCode: 'XK' },
  { label: 'Kuwait', dialCode: '+965', isoCode: 'KW' },
  { label: 'Kyrgyzstan', dialCode: '+996', isoCode: 'KG' },
  { label: 'Laos', dialCode: '+856', isoCode: 'LA' },
  { label: 'Latvia', dialCode: '+371', isoCode: 'LV' },
  { label: 'Lebanon', dialCode: '+961', isoCode: 'LB' },
  { label: 'Lesotho', dialCode: '+266', isoCode: 'LS' },
  { label: 'Liberia', dialCode: '+231', isoCode: 'LR' },
  { label: 'Libya', dialCode: '+218', isoCode: 'LY' },
  { label: 'Liechtenstein', dialCode: '+423', isoCode: 'LI' },
  { label: 'Lithuania', dialCode: '+370', isoCode: 'LT' },
  { label: 'Luxembourg', dialCode: '+352', isoCode: 'LU' },
  { label: 'Macau', dialCode: '+853', isoCode: 'MO' },
  { label: 'Madagascar', dialCode: '+261', isoCode: 'MG' },
  { label: 'Malawi', dialCode: '+265', isoCode: 'MW' },
  { label: 'Malaysia', dialCode: '+60', isoCode: 'MY' },
  { label: 'Maldives', dialCode: '+960', isoCode: 'MV' },
  { label: 'Mali', dialCode: '+223', isoCode: 'ML' },
  { label: 'Malta', dialCode: '+356', isoCode: 'MT' },
  { label: 'Marshall Islands', dialCode: '+692', isoCode: 'MH' },
  { label: 'Martinique', dialCode: '+596', isoCode: 'MQ' },
  { label: 'Mauritania', dialCode: '+222', isoCode: 'MR' },
  { label: 'Mauritius', dialCode: '+230', isoCode: 'MU' },
  { label: 'Mayotte', dialCode: '+262', isoCode: 'YT' },
  { label: 'Mexico', dialCode: '+52', isoCode: 'MX' },
  { label: 'Micronesia', dialCode: '+691', isoCode: 'FM' },
  { label: 'Moldova', dialCode: '+373', isoCode: 'MD' },
  { label: 'Monaco', dialCode: '+377', isoCode: 'MC' },
  { label: 'Mongolia', dialCode: '+976', isoCode: 'MN' },
  { label: 'Montenegro', dialCode: '+382', isoCode: 'ME' },
  { label: 'Montserrat', dialCode: '+1664', isoCode: 'MS' },
  { label: 'Morocco', dialCode: '+212', isoCode: 'MA' },
  { label: 'Mozambique', dialCode: '+258', isoCode: 'MZ' },
  { label: 'Myanmar', dialCode: '+95', isoCode: 'MM' },
  { label: 'Namibia', dialCode: '+264', isoCode: 'NA' },
  { label: 'Nauru', dialCode: '+674', isoCode: 'NR' },
  { label: 'Nepal', dialCode: '+977', isoCode: 'NP' },
  { label: 'Netherlands', dialCode: '+31', isoCode: 'NL' },
  { label: 'New Caledonia', dialCode: '+687', isoCode: 'NC' },
  { label: 'New Zealand', dialCode: '+64', isoCode: 'NZ' },
  { label: 'Nicaragua', dialCode: '+505', isoCode: 'NI' },
  { label: 'Niger', dialCode: '+227', isoCode: 'NE' },
  { label: 'Nigeria', dialCode: '+234', isoCode: 'NG' },
  { label: 'Niue', dialCode: '+683', isoCode: 'NU' },
  { label: 'Norfolk Island', dialCode: '+672', isoCode: 'NF' },
  { label: 'North Korea', dialCode: '+850', isoCode: 'KP' },
  { label: 'North Macedonia', dialCode: '+389', isoCode: 'MK' },
  { label: 'Northern Mariana Islands', dialCode: '+1670', isoCode: 'MP' },
  { label: 'Norway', dialCode: '+47', isoCode: 'NO' },
  { label: 'Oman', dialCode: '+968', isoCode: 'OM' },
  { label: 'Pakistan', dialCode: '+92', isoCode: 'PK' },
  { label: 'Palau', dialCode: '+680', isoCode: 'PW' },
  { label: 'Palestine', dialCode: '+970', isoCode: 'PS' },
  { label: 'Panama', dialCode: '+507', isoCode: 'PA' },
  { label: 'Papua New Guinea', dialCode: '+675', isoCode: 'PG' },
  { label: 'Paraguay', dialCode: '+595', isoCode: 'PY' },
  { label: 'Peru', dialCode: '+51', isoCode: 'PE' },
  { label: 'Philippines', dialCode: '+63', isoCode: 'PH' },
  { label: 'Poland', dialCode: '+48', isoCode: 'PL' },
  { label: 'Portugal', dialCode: '+351', isoCode: 'PT' },
  { label: 'Puerto Rico', dialCode: '+1787', isoCode: 'PR' },
  { label: 'Qatar', dialCode: '+974', isoCode: 'QA' },
  { label: 'Réunion', dialCode: '+262', isoCode: 'RE' },
  { label: 'Romania', dialCode: '+40', isoCode: 'RO' },
  { label: 'Russia', dialCode: '+7', isoCode: 'RU' },
  { label: 'Rwanda', dialCode: '+250', isoCode: 'RW' },
  { label: 'Saint Barthélemy', dialCode: '+590', isoCode: 'BL' },
  { label: 'Saint Helena', dialCode: '+290', isoCode: 'SH' },
  { label: 'Saint Kitts and Nevis', dialCode: '+1869', isoCode: 'KN' },
  { label: 'Saint Lucia', dialCode: '+1758', isoCode: 'LC' },
  { label: 'Saint Martin', dialCode: '+590', isoCode: 'MF' },
  { label: 'Saint Pierre and Miquelon', dialCode: '+508', isoCode: 'PM' },
  { label: 'Saint Vincent and the Grenadines', dialCode: '+1784', isoCode: 'VC' },
  { label: 'Samoa', dialCode: '+685', isoCode: 'WS' },
  { label: 'San Marino', dialCode: '+378', isoCode: 'SM' },
  { label: 'São Tomé and Príncipe', dialCode: '+239', isoCode: 'ST' },
  { label: 'Saudi Arabia', dialCode: '+966', isoCode: 'SA' },
  { label: 'Senegal', dialCode: '+221', isoCode: 'SN' },
  { label: 'Serbia', dialCode: '+381', isoCode: 'RS' },
  { label: 'Seychelles', dialCode: '+248', isoCode: 'SC' },
  { label: 'Sierra Leone', dialCode: '+232', isoCode: 'SL' },
  { label: 'Singapore', dialCode: '+65', isoCode: 'SG' },
  { label: 'Sint Maarten', dialCode: '+1721', isoCode: 'SX' },
  { label: 'Slovakia', dialCode: '+421', isoCode: 'SK' },
  { label: 'Slovenia', dialCode: '+386', isoCode: 'SI' },
  { label: 'Solomon Islands', dialCode: '+677', isoCode: 'SB' },
  { label: 'Somalia', dialCode: '+252', isoCode: 'SO' },
  { label: 'South Africa', dialCode: '+27', isoCode: 'ZA' },
  { label: 'South Korea', dialCode: '+82', isoCode: 'KR' },
  { label: 'South Sudan', dialCode: '+211', isoCode: 'SS' },
  { label: 'Spain', dialCode: '+34', isoCode: 'ES' },
  { label: 'Sri Lanka', dialCode: '+94', isoCode: 'LK' },
  { label: 'Sudan', dialCode: '+249', isoCode: 'SD' },
  { label: 'Suriname', dialCode: '+597', isoCode: 'SR' },
  { label: 'Svalbard and Jan Mayen', dialCode: '+47', isoCode: 'SJ' },
  { label: 'Sweden', dialCode: '+46', isoCode: 'SE' },
  { label: 'Switzerland', dialCode: '+41', isoCode: 'CH' },
  { label: 'Syria', dialCode: '+963', isoCode: 'SY' },
  { label: 'Taiwan', dialCode: '+886', isoCode: 'TW' },
  { label: 'Tajikistan', dialCode: '+992', isoCode: 'TJ' },
  { label: 'Tanzania', dialCode: '+255', isoCode: 'TZ' },
  { label: 'Thailand', dialCode: '+66', isoCode: 'TH' },
  { label: 'Timor-Leste', dialCode: '+670', isoCode: 'TL' },
  { label: 'Togo', dialCode: '+228', isoCode: 'TG' },
  { label: 'Tokelau', dialCode: '+690', isoCode: 'TK' },
  { label: 'Tonga', dialCode: '+676', isoCode: 'TO' },
  { label: 'Trinidad and Tobago', dialCode: '+1868', isoCode: 'TT' },
  { label: 'Tunisia', dialCode: '+216', isoCode: 'TN' },
  { label: 'Turkey', dialCode: '+90', isoCode: 'TR' },
  { label: 'Turkmenistan', dialCode: '+993', isoCode: 'TM' },
  { label: 'Turks and Caicos Islands', dialCode: '+1649', isoCode: 'TC' },
  { label: 'Tuvalu', dialCode: '+688', isoCode: 'TV' },
  { label: 'U.S. Virgin Islands', dialCode: '+1340', isoCode: 'VI' },
  { label: 'Uganda', dialCode: '+256', isoCode: 'UG' },
  { label: 'Ukraine', dialCode: '+380', isoCode: 'UA' },
  { label: 'United Arab Emirates', dialCode: '+971', isoCode: 'AE' },
  { label: 'United Kingdom', dialCode: '+44', isoCode: 'GB' },
  { label: 'United States', dialCode: '+1', isoCode: 'US' },
  { label: 'Uruguay', dialCode: '+598', isoCode: 'UY' },
  { label: 'Uzbekistan', dialCode: '+998', isoCode: 'UZ' },
  { label: 'Vanuatu', dialCode: '+678', isoCode: 'VU' },
  { label: 'Vatican City', dialCode: '+39', isoCode: 'VA' },
  { label: 'Venezuela', dialCode: '+58', isoCode: 'VE' },
  { label: 'Vietnam', dialCode: '+84', isoCode: 'VN' },
  { label: 'Wallis and Futuna', dialCode: '+681', isoCode: 'WF' },
  { label: 'Western Sahara', dialCode: '+212', isoCode: 'EH' },
  { label: 'Yemen', dialCode: '+967', isoCode: 'YE' },
  { label: 'Zambia', dialCode: '+260', isoCode: 'ZM' },
  { label: 'Zimbabwe', dialCode: '+263', isoCode: 'ZW' },
];

/** Full country list with `value = isoCode.toLowerCase()`. */
export const ALL_COUNTRY_OPTIONS: ReadonlyArray<CountryEntry> = ALL_COUNTRIES.map(
  (c) => ({ ...c, value: c.isoCode.toLowerCase() }),
);

/**
 * Country options ordered with priority countries first, then the rest
 * alphabetically. This ordering powers the country-code selector UI.
 */
export const COUNTRY_OPTIONS: ReadonlyArray<CountryEntry> = (() => {
  const byIso = new Map(ALL_COUNTRY_OPTIONS.map((c) => [c.isoCode, c] as const));
  const priority: CountryEntry[] = [];
  for (const iso of PRIORITY_COUNTRY_ISO) {
    const entry = byIso.get(iso);
    if (entry) priority.push(entry);
  }
  const prioritySet = new Set(PRIORITY_COUNTRY_ISO);
  const rest = ALL_COUNTRY_OPTIONS.filter((c) => !prioritySet.has(c.isoCode));
  return [...priority, ...rest];
})();

export function findCountryByValue(value: string): CountryEntry | undefined {
  return COUNTRY_OPTIONS.find((c) => c.value === value);
}

export function findCountryByDialCode(dialCode: string): CountryEntry | undefined {
  return COUNTRY_OPTIONS.find((c) => c.dialCode === dialCode);
}
