namespace OetLearner.Api.Contracts;

public sealed record AdminLaunchReadinessSettingsResponse(
    bool EnforceClientVersionGate,
    string MobileMinSupportedVersion,
    string MobileLatestVersion,
    bool MobileForceUpdate,
    string? IosAppStoreUrl,
    string? AndroidPlayStoreUrl,
    string? IosBundleId,
    string? AppleTeamId,
    string? AppleAssociatedDomainStatus,
    string? AppleUniversalLinksStatus,
    string? IosSigningProfileReference,
    string? IosIapStatus,
    string? IosPushStatus,
    string? AndroidPackageName,
    string? AndroidSha256Fingerprints,
    string? AndroidSigningKeyReference,
    string? AndroidAssetLinksStatus,
    string? AndroidIapStatus,
    string? AndroidPushStatus,
    string DesktopMinSupportedVersion,
    string DesktopLatestVersion,
    bool DesktopForceUpdate,
    string? DesktopUpdateFeedUrl,
    string? DesktopUpdateChannel,
    string? WindowsSigningStatus,
    string? MacSigningStatus,
    string? LinuxSigningStatus,
    string? DeviceValidationEvidenceUrl,
    string? DeviceValidationNotes,
    string? RealtimeLegalApprovalStatus,
    string? RealtimePrivacyApprovalStatus,
    string? RealtimeProtectedSmokeStatus,
    string? RealtimeEvidenceUrl,
    bool RealtimeSpendCapApproved,
    bool RealtimeTopologyApproved,
    string? ReleaseOwnerApprovalStatus,
    string? LaunchNotes,
    DateTimeOffset UpdatedAt,
    string? UpdatedByAdminId,
    string? UpdatedByAdminName);

public sealed record AdminLaunchReadinessSettingsRequest(
    bool? EnforceClientVersionGate,
    string? MobileMinSupportedVersion,
    string? MobileLatestVersion,
    bool? MobileForceUpdate,
    string? IosAppStoreUrl,
    string? AndroidPlayStoreUrl,
    string? IosBundleId,
    string? AppleTeamId,
    string? AppleAssociatedDomainStatus,
    string? AppleUniversalLinksStatus,
    string? IosSigningProfileReference,
    string? IosIapStatus,
    string? IosPushStatus,
    string? AndroidPackageName,
    string? AndroidSha256Fingerprints,
    string? AndroidSigningKeyReference,
    string? AndroidAssetLinksStatus,
    string? AndroidIapStatus,
    string? AndroidPushStatus,
    string? DesktopMinSupportedVersion,
    string? DesktopLatestVersion,
    bool? DesktopForceUpdate,
    string? DesktopUpdateFeedUrl,
    string? DesktopUpdateChannel,
    string? WindowsSigningStatus,
    string? MacSigningStatus,
    string? LinuxSigningStatus,
    string? DeviceValidationEvidenceUrl,
    string? DeviceValidationNotes,
    string? RealtimeLegalApprovalStatus,
    string? RealtimePrivacyApprovalStatus,
    string? RealtimeProtectedSmokeStatus,
    string? RealtimeEvidenceUrl,
    bool? RealtimeSpendCapApproved,
    bool? RealtimeTopologyApproved,
    string? ReleaseOwnerApprovalStatus,
    string? LaunchNotes);

public sealed record PublicAppReleaseSettingsResponse(
    string Platform,
    string MinVersion,
    string LatestVersion,
    bool ForceUpdate,
    string? StoreUrl,
    string? UpdateFeedUrl,
    string? Channel);

/// <summary>
/// Decision returned by the client-version gate for a single request. When
/// <see cref="Blocked"/> is true the request should be short-circuited with
/// 426 Upgrade Required.
/// </summary>
public sealed record ClientGateDecision(
    bool Blocked,
    string MinVersion,
    string? StoreUrl,
    string? UpdateFeedUrl);
