namespace OetLearner.Api.Configuration;

/// <summary>
/// EasyKash payment configuration (Egypt-first, also multi-currency). Hosted
/// Direct-Pay flow: POST /api/directpayv1/pay returns a redirect URL; the buyer
/// pays on EasyKash's hosted page; a server-to-server callback (HMAC-SHA512)
/// confirms the payment. Inactive until <see cref="ApiKey"/> AND
/// <see cref="HmacSecret"/> are both set (the HMAC secret is generated by
/// EasyKash only after the Callback URL + payment methods are saved in their
/// dashboard).
/// </summary>
public sealed class EasyKashOptions
{
    public string ApiBaseUrl { get; set; } = "https://back.easykash.net";

    /// <summary>API key sent verbatim in the <c>authorization</c> header of the Pay API request.</summary>
    public string? ApiKey { get; set; }

    /// <summary>HMAC secret used to verify the SHA-512 callback signature (<c>signatureHash</c>).</summary>
    public string? HmacSecret { get; set; }

    /// <summary>
    /// Optional EasyKash payment-method ids to offer (e.g. 2=card, 4=wallet,
    /// 5=Fawry). When empty, EasyKash shows whatever the merchant enabled in the
    /// dashboard.
    /// </summary>
    public int[] PaymentOptions { get; set; } = System.Array.Empty<int>();

    /// <summary>
    /// How the amount is charged: <c>"passthrough"</c> sends the quote currency
    /// as-is (e.g. GBP 100); <c>"egp"</c> FX-converts the quote to EGP before
    /// charging. Admin-switchable. Defaults to passthrough.
    /// </summary>
    public string CurrencyMode { get; set; } = "passthrough";

    public string? SuccessUrl { get; set; }
    public string? CancelUrl { get; set; }
}
