import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import {
  OetStatementOfResultsCard,
  CHART,
  BANDS,
  scoreToY,
  subtestColumnX,
  labelFitsInside,
} from './OetStatementOfResultsCard';
import {
  SOR_FIXTURE_MEDICINE_UK,
  SOR_FIXTURE_MEDICINE_USA,
  SOR_FIXTURE_BORDERLINE,
  SOR_FIXTURE_PERFECT,
  SOR_FIXTURE_FAIL,
} from '@/lib/fixtures/oet-sor-fixtures';

describe('scoreToY math', () => {
  it('maps 500 to the top of the plot region', () => {
    const y = scoreToY(500);
    expect(y).toBe(CHART.padTop);
  });

  it('maps 0 to the bottom of the plot region', () => {
    const y = scoreToY(0);
    expect(y).toBe(CHART.height - CHART.padBottom);
  });

  it('maps 250 to the vertical midpoint', () => {
    const mid = scoreToY(250);
    const top = scoreToY(500);
    const bot = scoreToY(0);
    expect(mid).toBeCloseTo((top + bot) / 2, 5);
  });

  it('clamps scores above 500 and below 0', () => {
    expect(scoreToY(700)).toBe(scoreToY(500));
    expect(scoreToY(-50)).toBe(scoreToY(0));
  });

  it.each([
    [100, 'D'] as const,
    [200, 'C'] as const,
    [300, 'C+'] as const,
    [350, 'B'] as const,
    [450, 'A'] as const,
  ])('threshold %i is on a band boundary', (score, _expectedBandTop) => {
    // The y-coordinate of a threshold must equal the top-edge y of the band
    // whose min equals that threshold.
    const band = BANDS.find((b) => b.min === score)!;
    const bandTopY = scoreToY(band.max);
    const scoreY = scoreToY(score);
    expect(scoreY).toBeGreaterThan(bandTopY);
  });
});

describe('band geometry', () => {
  it('has exactly six bands covering 0 to 500 continuously', () => {
    const sorted = [...BANDS].sort((a, b) => a.min - b.min);
    expect(sorted[0].min).toBe(0);
    expect(sorted[sorted.length - 1].max).toBe(500);
    for (let i = 1; i < sorted.length; i++) {
      expect(sorted[i].min).toBe(sorted[i - 1].max);
    }
  });
});

describe('subtestColumnX', () => {
  it('returns four equal-width columns in left-to-right order', () => {
    const cols = [0, 1, 2, 3].map(subtestColumnX);
    cols.slice(1).forEach((c, i) => {
      expect(c.x).toBeGreaterThan(cols[i].x);
      expect(c.w).toBeCloseTo(cols[0].w, 5);
    });
  });
});

describe('labelFitsInside', () => {
  it('fits a label inside the bar for a mid-range score', () => {
    expect(labelFitsInside(300)).toBe(true);
  });
  it('drops the label outside when the bar hugs the top edge', () => {
    // score 500 → bar centre at the top of the plot region; label won't fit inside.
    expect(labelFitsInside(500)).toBe(false);
  });
  it('drops the label outside when the bar hugs the bottom edge', () => {
    expect(labelFitsInside(0)).toBe(false);
  });
});

describe('OetStatementOfResultsCard rendering', () => {
  it('renders all four score values in the summary strip', () => {
    render(<OetStatementOfResultsCard data={SOR_FIXTURE_MEDICINE_UK} />);
    // Each score is drawn twice (strip + chart bar). Use getAllByText.
    expect(screen.getAllByText('430').length).toBeGreaterThan(0);
    expect(screen.getAllByText('420').length).toBeGreaterThan(0);
    expect(screen.getAllByText('350').length).toBeGreaterThan(0);
    expect(screen.getAllByText('370').length).toBeGreaterThan(0);
  });

  it('shows the practice disclaimer on practice results', () => {
    render(<OetStatementOfResultsCard data={SOR_FIXTURE_MEDICINE_UK} />);
    expect(
      screen.getByText(/practice result generated by the OET Prep platform/i),
    ).toBeInTheDocument();
  });

  it('suppresses the disclaimer when asked (internal QA only)', () => {
    render(
      <OetStatementOfResultsCard
        data={SOR_FIXTURE_MEDICINE_UK}
        suppressPracticeDisclaimer
      />,
    );
    expect(screen.queryByText(/practice result generated/i)).toBeNull();
  });

  it('renders the candidate name in the accessible heading', () => {
    render(<OetStatementOfResultsCard data={SOR_FIXTURE_MEDICINE_UK} />);
    expect(
      screen.getByText(/OET Statement of Results for Ms Sarah Miller/i),
    ).toBeInTheDocument();
  });

  it.each([
    SOR_FIXTURE_MEDICINE_UK,
    SOR_FIXTURE_MEDICINE_USA,
    SOR_FIXTURE_BORDERLINE,
    SOR_FIXTURE_PERFECT,
    SOR_FIXTURE_FAIL,
  ])('renders fixture %#', (fixture) => {
    const { container } = render(<OetStatementOfResultsCard data={fixture} />);
    // The SVG chart must be present.
    expect(container.querySelector('svg[role="img"]')).toBeTruthy();
    // The verification footer must always be present.
    expect(
      screen.getByText(/verification portal/i),
    ).toBeInTheDocument();
  });

  it('exposes an accessible data table for screen readers', () => {
    render(<OetStatementOfResultsCard data={SOR_FIXTURE_MEDICINE_UK} />);
    const caption = screen.getByText(/Statement of Results — data table/i);
    expect(caption).toBeInTheDocument();
  });
});
